// Copyright 2019 - 2022 The Samply Community
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir

// THIS FILE IS GENERATED BY https://github.com/samply/golang-fhir-models
// PLEASE DO NOT EDIT BY HAND

// Address is documented here http://hl7.org/fhir/StructureDefinition/Address
type Address struct {
	Id                *string             `bson:"id,omitempty" json:"id,omitempty"`
	IdElement         *PrimitiveElement   `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension         []Extension         `bson:"extension,omitempty" json:"extension,omitempty"`
	Use               *AddressUse         `bson:"use,omitempty" json:"use,omitempty"`
	UseElement        *PrimitiveElement   `bson:"_use,omitempty" json:"_use,omitempty"`
	Type              *AddressType        `bson:"type,omitempty" json:"type,omitempty"`
	TypeElement       *PrimitiveElement   `bson:"_type,omitempty" json:"_type,omitempty"`
	Text              *string             `bson:"text,omitempty" json:"text,omitempty"`
	TextElement       *PrimitiveElement   `bson:"_text,omitempty" json:"_text,omitempty"`
	Line              []string            `bson:"line,omitempty" json:"line,omitempty"`
	LineElement       []*PrimitiveElement `bson:"_line,omitempty" json:"_line,omitempty"`
	City              *string             `bson:"city,omitempty" json:"city,omitempty"`
	CityElement       *PrimitiveElement   `bson:"_city,omitempty" json:"_city,omitempty"`
	District          *string             `bson:"district,omitempty" json:"district,omitempty"`
	DistrictElement   *PrimitiveElement   `bson:"_district,omitempty" json:"_district,omitempty"`
	State             *string             `bson:"state,omitempty" json:"state,omitempty"`
	StateElement      *PrimitiveElement   `bson:"_state,omitempty" json:"_state,omitempty"`
	PostalCode        *string             `bson:"postalCode,omitempty" json:"postalCode,omitempty"`
	PostalCodeElement *PrimitiveElement   `bson:"_postalCode,omitempty" json:"_postalCode,omitempty"`
	Country           *string             `bson:"country,omitempty" json:"country,omitempty"`
	CountryElement    *PrimitiveElement   `bson:"_country,omitempty" json:"_country,omitempty"`
	Period            *Period             `bson:"period,omitempty" json:"period,omitempty"`
}
