// Copyright 2019 - 2022 The Samply Community
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir

// THIS FILE IS GENERATED BY https://github.com/samply/golang-fhir-models
// PLEASE DO NOT EDIT BY HAND

// ContactPoint is documented here http://hl7.org/fhir/StructureDefinition/ContactPoint
type ContactPoint struct {
	Id            *string             `bson:"id,omitempty" json:"id,omitempty"`
	IdElement     *PrimitiveElement   `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension     []Extension         `bson:"extension,omitempty" json:"extension,omitempty"`
	System        *ContactPointSystem `bson:"system,omitempty" json:"system,omitempty"`
	SystemElement *PrimitiveElement   `bson:"_system,omitempty" json:"_system,omitempty"`
	Value         *string             `bson:"value,omitempty" json:"value,omitempty"`
	ValueElement  *PrimitiveElement   `bson:"_value,omitempty" json:"_value,omitempty"`
	Use           *ContactPointUse    `bson:"use,omitempty" json:"use,omitempty"`
	UseElement    *PrimitiveElement   `bson:"_use,omitempty" json:"_use,omitempty"`
	Rank          *int                `bson:"rank,omitempty" json:"rank,omitempty"`
	RankElement   *PrimitiveElement   `bson:"_rank,omitempty" json:"_rank,omitempty"`
	Period        *Period             `bson:"period,omitempty" json:"period,omitempty"`
}
