// Copyright 2019 - 2022 The Samply Community
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir

import "encoding/json"

// THIS FILE IS GENERATED BY https://github.com/samply/golang-fhir-models
// PLEASE DO NOT EDIT BY HAND

// EvidenceVariable is documented here http://hl7.org/fhir/StructureDefinition/EvidenceVariable
type EvidenceVariable struct {
	Id                    *string                          `bson:"id,omitempty" json:"id,omitempty"`
	IdElement             *PrimitiveElement                `bson:"_id,omitempty" json:"_id,omitempty"`
	Meta                  *Meta                            `bson:"meta,omitempty" json:"meta,omitempty"`
	ImplicitRules         *string                          `bson:"implicitRules,omitempty" json:"implicitRules,omitempty"`
	ImplicitRulesElement  *PrimitiveElement                `bson:"_implicitRules,omitempty" json:"_implicitRules,omitempty"`
	Language              *string                          `bson:"language,omitempty" json:"language,omitempty"`
	LanguageElement       *PrimitiveElement                `bson:"_language,omitempty" json:"_language,omitempty"`
	Text                  *Narrative                       `bson:"text,omitempty" json:"text,omitempty"`
	Extension             []Extension                      `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension     []Extension                      `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Url                   *string                          `bson:"url,omitempty" json:"url,omitempty"`
	UrlElement            *PrimitiveElement                `bson:"_url,omitempty" json:"_url,omitempty"`
	Identifier            []Identifier                     `bson:"identifier,omitempty" json:"identifier,omitempty"`
	Version               *string                          `bson:"version,omitempty" json:"version,omitempty"`
	VersionElement        *PrimitiveElement                `bson:"_version,omitempty" json:"_version,omitempty"`
	Name                  *string                          `bson:"name,omitempty" json:"name,omitempty"`
	NameElement           *PrimitiveElement                `bson:"_name,omitempty" json:"_name,omitempty"`
	Title                 *string                          `bson:"title,omitempty" json:"title,omitempty"`
	TitleElement          *PrimitiveElement                `bson:"_title,omitempty" json:"_title,omitempty"`
	ShortTitle            *string                          `bson:"shortTitle,omitempty" json:"shortTitle,omitempty"`
	ShortTitleElement     *PrimitiveElement                `bson:"_shortTitle,omitempty" json:"_shortTitle,omitempty"`
	Subtitle              *string                          `bson:"subtitle,omitempty" json:"subtitle,omitempty"`
	SubtitleElement       *PrimitiveElement                `bson:"_subtitle,omitempty" json:"_subtitle,omitempty"`
	Status                PublicationStatus                `bson:"status" json:"status"`
	StatusElement         *PrimitiveElement                `bson:"_status,omitempty" json:"_status,omitempty"`
	Date                  *string                          `bson:"date,omitempty" json:"date,omitempty"`
	DateElement           *PrimitiveElement                `bson:"_date,omitempty" json:"_date,omitempty"`
	Publisher             *string                          `bson:"publisher,omitempty" json:"publisher,omitempty"`
	PublisherElement      *PrimitiveElement                `bson:"_publisher,omitempty" json:"_publisher,omitempty"`
	Contact               []ContactDetail                  `bson:"contact,omitempty" json:"contact,omitempty"`
	Description           *string                          `bson:"description,omitempty" json:"description,omitempty"`
	DescriptionElement    *PrimitiveElement                `bson:"_description,omitempty" json:"_description,omitempty"`
	Note                  []Annotation                     `bson:"note,omitempty" json:"note,omitempty"`
	UseContext            []UsageContext                   `bson:"useContext,omitempty" json:"useContext,omitempty"`
	Jurisdiction          []CodeableConcept                `bson:"jurisdiction,omitempty" json:"jurisdiction,omitempty"`
	Copyright             *string                          `bson:"copyright,omitempty" json:"copyright,omitempty"`
	CopyrightElement      *PrimitiveElement                `bson:"_copyright,omitempty" json:"_copyright,omitempty"`
	ApprovalDate          *string                          `bson:"approvalDate,omitempty" json:"approvalDate,omitempty"`
	ApprovalDateElement   *PrimitiveElement                `bson:"_approvalDate,omitempty" json:"_approvalDate,omitempty"`
	LastReviewDate        *string                          `bson:"lastReviewDate,omitempty" json:"lastReviewDate,omitempty"`
	LastReviewDateElement *PrimitiveElement                `bson:"_lastReviewDate,omitempty" json:"_lastReviewDate,omitempty"`
	EffectivePeriod       *Period                          `bson:"effectivePeriod,omitempty" json:"effectivePeriod,omitempty"`
	Topic                 []CodeableConcept                `bson:"topic,omitempty" json:"topic,omitempty"`
	Author                []ContactDetail                  `bson:"author,omitempty" json:"author,omitempty"`
	Editor                []ContactDetail                  `bson:"editor,omitempty" json:"editor,omitempty"`
	Reviewer              []ContactDetail                  `bson:"reviewer,omitempty" json:"reviewer,omitempty"`
	Endorser              []ContactDetail                  `bson:"endorser,omitempty" json:"endorser,omitempty"`
	RelatedArtifact       []RelatedArtifact                `bson:"relatedArtifact,omitempty" json:"relatedArtifact,omitempty"`
	Type                  *EvidenceVariableType            `bson:"type,omitempty" json:"type,omitempty"`
	TypeElement           *PrimitiveElement                `bson:"_type,omitempty" json:"_type,omitempty"`
	Characteristic        []EvidenceVariableCharacteristic `bson:"characteristic" json:"characteristic"`
}
type EvidenceVariableCharacteristic struct {
	Id                                  *string            `bson:"id,omitempty" json:"id,omitempty"`
	IdElement                           *PrimitiveElement  `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension                           []Extension        `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension                   []Extension        `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Description                         *string            `bson:"description,omitempty" json:"description,omitempty"`
	DescriptionElement                  *PrimitiveElement  `bson:"_description,omitempty" json:"_description,omitempty"`
	DefinitionReference                 *Reference         `bson:"definitionReference,omitempty" json:"definitionReference,omitempty"`
	DefinitionCanonical                 *string            `bson:"definitionCanonical,omitempty" json:"definitionCanonical,omitempty"`
	DefinitionCanonicalElement          *PrimitiveElement  `bson:"_definitionCanonical,omitempty" json:"_definitionCanonical,omitempty"`
	DefinitionCodeableConcept           *CodeableConcept   `bson:"definitionCodeableConcept,omitempty" json:"definitionCodeableConcept,omitempty"`
	DefinitionExpression                *Expression        `bson:"definitionExpression,omitempty" json:"definitionExpression,omitempty"`
	DefinitionDataRequirement           *DataRequirement   `bson:"definitionDataRequirement,omitempty" json:"definitionDataRequirement,omitempty"`
	DefinitionTriggerDefinition         *TriggerDefinition `bson:"definitionTriggerDefinition,omitempty" json:"definitionTriggerDefinition,omitempty"`
	UsageContext                        []UsageContext     `bson:"usageContext,omitempty" json:"usageContext,omitempty"`
	Exclude                             *bool              `bson:"exclude,omitempty" json:"exclude,omitempty"`
	ExcludeElement                      *PrimitiveElement  `bson:"_exclude,omitempty" json:"_exclude,omitempty"`
	ParticipantEffectiveDateTime        *string            `bson:"participantEffectiveDateTime,omitempty" json:"participantEffectiveDateTime,omitempty"`
	ParticipantEffectiveDateTimeElement *PrimitiveElement  `bson:"_participantEffectiveDateTime,omitempty" json:"_participantEffectiveDateTime,omitempty"`
	ParticipantEffectivePeriod          *Period            `bson:"participantEffectivePeriod,omitempty" json:"participantEffectivePeriod,omitempty"`
	ParticipantEffectiveDuration        *Duration          `bson:"participantEffectiveDuration,omitempty" json:"participantEffectiveDuration,omitempty"`
	ParticipantEffectiveTiming          *Timing            `bson:"participantEffectiveTiming,omitempty" json:"participantEffectiveTiming,omitempty"`
	TimeFromStart                       *Duration          `bson:"timeFromStart,omitempty" json:"timeFromStart,omitempty"`
	GroupMeasure                        *GroupMeasure      `bson:"groupMeasure,omitempty" json:"groupMeasure,omitempty"`
	GroupMeasureElement                 *PrimitiveElement  `bson:"_groupMeasure,omitempty" json:"_groupMeasure,omitempty"`
}
type OtherEvidenceVariable EvidenceVariable

// MarshalJSON marshals the given EvidenceVariable as JSON into a byte slice
func (r EvidenceVariable) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		OtherEvidenceVariable
		ResourceType string `json:"resourceType"`
	}{
		OtherEvidenceVariable: OtherEvidenceVariable(r),
		ResourceType:          "EvidenceVariable",
	})
}

// UnmarshalEvidenceVariable unmarshals a EvidenceVariable.
func UnmarshalEvidenceVariable(b []byte) (EvidenceVariable, error) {
	var evidenceVariable EvidenceVariable
	if err := json.Unmarshal(b, &evidenceVariable); err != nil {
		return evidenceVariable, err
	}
	return evidenceVariable, nil
}
