// Copyright 2019 - 2022 The Samply Community
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir

// THIS FILE IS GENERATED BY https://github.com/samply/golang-fhir-models
// PLEASE DO NOT EDIT BY HAND

// Expression is documented here http://hl7.org/fhir/StructureDefinition/Expression
type Expression struct {
	Id                 *string           `bson:"id,omitempty" json:"id,omitempty"`
	IdElement          *PrimitiveElement `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension          []Extension       `bson:"extension,omitempty" json:"extension,omitempty"`
	Description        *string           `bson:"description,omitempty" json:"description,omitempty"`
	DescriptionElement *PrimitiveElement `bson:"_description,omitempty" json:"_description,omitempty"`
	Name               *string           `bson:"name,omitempty" json:"name,omitempty"`
	NameElement        *PrimitiveElement `bson:"_name,omitempty" json:"_name,omitempty"`
	Language           string            `bson:"language" json:"language"`
	LanguageElement    *PrimitiveElement `bson:"_language,omitempty" json:"_language,omitempty"`
	Expression         *string           `bson:"expression,omitempty" json:"expression,omitempty"`
	ExpressionElement  *PrimitiveElement `bson:"_expression,omitempty" json:"_expression,omitempty"`
	Reference          *string           `bson:"reference,omitempty" json:"reference,omitempty"`
	ReferenceElement   *PrimitiveElement `bson:"_reference,omitempty" json:"_reference,omitempty"`
}
