// Copyright 2019 - 2022 The Samply Community
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir

import "encoding/json"

// THIS FILE IS GENERATED BY https://github.com/samply/golang-fhir-models
// PLEASE DO NOT EDIT BY HAND

// FamilyMemberHistory is documented here http://hl7.org/fhir/StructureDefinition/FamilyMemberHistory
type FamilyMemberHistory struct {
	Id                           *string                        `bson:"id,omitempty" json:"id,omitempty"`
	IdElement                    *PrimitiveElement              `bson:"_id,omitempty" json:"_id,omitempty"`
	Meta                         *Meta                          `bson:"meta,omitempty" json:"meta,omitempty"`
	ImplicitRules                *string                        `bson:"implicitRules,omitempty" json:"implicitRules,omitempty"`
	ImplicitRulesElement         *PrimitiveElement              `bson:"_implicitRules,omitempty" json:"_implicitRules,omitempty"`
	Language                     *string                        `bson:"language,omitempty" json:"language,omitempty"`
	LanguageElement              *PrimitiveElement              `bson:"_language,omitempty" json:"_language,omitempty"`
	Text                         *Narrative                     `bson:"text,omitempty" json:"text,omitempty"`
	Extension                    []Extension                    `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension            []Extension                    `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Identifier                   []Identifier                   `bson:"identifier,omitempty" json:"identifier,omitempty"`
	InstantiatesCanonical        []string                       `bson:"instantiatesCanonical,omitempty" json:"instantiatesCanonical,omitempty"`
	InstantiatesCanonicalElement []*PrimitiveElement            `bson:"_instantiatesCanonical,omitempty" json:"_instantiatesCanonical,omitempty"`
	InstantiatesUri              []string                       `bson:"instantiatesUri,omitempty" json:"instantiatesUri,omitempty"`
	InstantiatesUriElement       []*PrimitiveElement            `bson:"_instantiatesUri,omitempty" json:"_instantiatesUri,omitempty"`
	Status                       FamilyHistoryStatus            `bson:"status" json:"status"`
	StatusElement                *PrimitiveElement              `bson:"_status,omitempty" json:"_status,omitempty"`
	DataAbsentReason             *CodeableConcept               `bson:"dataAbsentReason,omitempty" json:"dataAbsentReason,omitempty"`
	Patient                      Reference                      `bson:"patient" json:"patient"`
	Date                         *string                        `bson:"date,omitempty" json:"date,omitempty"`
	DateElement                  *PrimitiveElement              `bson:"_date,omitempty" json:"_date,omitempty"`
	Name                         *string                        `bson:"name,omitempty" json:"name,omitempty"`
	NameElement                  *PrimitiveElement              `bson:"_name,omitempty" json:"_name,omitempty"`
	Relationship                 CodeableConcept                `bson:"relationship" json:"relationship"`
	Sex                          *CodeableConcept               `bson:"sex,omitempty" json:"sex,omitempty"`
	BornPeriod                   *Period                        `bson:"bornPeriod,omitempty" json:"bornPeriod,omitempty"`
	BornDate                     *string                        `bson:"bornDate,omitempty" json:"bornDate,omitempty"`
	BornDateElement              *PrimitiveElement              `bson:"_bornDate,omitempty" json:"_bornDate,omitempty"`
	BornString                   *string                        `bson:"bornString,omitempty" json:"bornString,omitempty"`
	BornStringElement            *PrimitiveElement              `bson:"_bornString,omitempty" json:"_bornString,omitempty"`
	AgeAge                       *Age                           `bson:"ageAge,omitempty" json:"ageAge,omitempty"`
	AgeRange                     *Range                         `bson:"ageRange,omitempty" json:"ageRange,omitempty"`
	AgeString                    *string                        `bson:"ageString,omitempty" json:"ageString,omitempty"`
	AgeStringElement             *PrimitiveElement              `bson:"_ageString,omitempty" json:"_ageString,omitempty"`
	EstimatedAge                 *bool                          `bson:"estimatedAge,omitempty" json:"estimatedAge,omitempty"`
	EstimatedAgeElement          *PrimitiveElement              `bson:"_estimatedAge,omitempty" json:"_estimatedAge,omitempty"`
	DeceasedBoolean              *bool                          `bson:"deceasedBoolean,omitempty" json:"deceasedBoolean,omitempty"`
	DeceasedBooleanElement       *PrimitiveElement              `bson:"_deceasedBoolean,omitempty" json:"_deceasedBoolean,omitempty"`
	DeceasedAge                  *Age                           `bson:"deceasedAge,omitempty" json:"deceasedAge,omitempty"`
	DeceasedRange                *Range                         `bson:"deceasedRange,omitempty" json:"deceasedRange,omitempty"`
	DeceasedDate                 *string                        `bson:"deceasedDate,omitempty" json:"deceasedDate,omitempty"`
	DeceasedDateElement          *PrimitiveElement              `bson:"_deceasedDate,omitempty" json:"_deceasedDate,omitempty"`
	DeceasedString               *string                        `bson:"deceasedString,omitempty" json:"deceasedString,omitempty"`
	DeceasedStringElement        *PrimitiveElement              `bson:"_deceasedString,omitempty" json:"_deceasedString,omitempty"`
	ReasonCode                   []CodeableConcept              `bson:"reasonCode,omitempty" json:"reasonCode,omitempty"`
	ReasonReference              []Reference                    `bson:"reasonReference,omitempty" json:"reasonReference,omitempty"`
	Note                         []Annotation                   `bson:"note,omitempty" json:"note,omitempty"`
	Condition                    []FamilyMemberHistoryCondition `bson:"condition,omitempty" json:"condition,omitempty"`
}
type FamilyMemberHistoryCondition struct {
	Id                        *string           `bson:"id,omitempty" json:"id,omitempty"`
	IdElement                 *PrimitiveElement `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension                 []Extension       `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension         []Extension       `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Code                      CodeableConcept   `bson:"code" json:"code"`
	Outcome                   *CodeableConcept  `bson:"outcome,omitempty" json:"outcome,omitempty"`
	ContributedToDeath        *bool             `bson:"contributedToDeath,omitempty" json:"contributedToDeath,omitempty"`
	ContributedToDeathElement *PrimitiveElement `bson:"_contributedToDeath,omitempty" json:"_contributedToDeath,omitempty"`
	OnsetAge                  *Age              `bson:"onsetAge,omitempty" json:"onsetAge,omitempty"`
	OnsetRange                *Range            `bson:"onsetRange,omitempty" json:"onsetRange,omitempty"`
	OnsetPeriod               *Period           `bson:"onsetPeriod,omitempty" json:"onsetPeriod,omitempty"`
	OnsetString               *string           `bson:"onsetString,omitempty" json:"onsetString,omitempty"`
	OnsetStringElement        *PrimitiveElement `bson:"_onsetString,omitempty" json:"_onsetString,omitempty"`
	Note                      []Annotation      `bson:"note,omitempty" json:"note,omitempty"`
}
type OtherFamilyMemberHistory FamilyMemberHistory

// MarshalJSON marshals the given FamilyMemberHistory as JSON into a byte slice
func (r FamilyMemberHistory) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		OtherFamilyMemberHistory
		ResourceType string `json:"resourceType"`
	}{
		OtherFamilyMemberHistory: OtherFamilyMemberHistory(r),
		ResourceType:             "FamilyMemberHistory",
	})
}

// UnmarshalFamilyMemberHistory unmarshals a FamilyMemberHistory.
func UnmarshalFamilyMemberHistory(b []byte) (FamilyMemberHistory, error) {
	var familyMemberHistory FamilyMemberHistory
	if err := json.Unmarshal(b, &familyMemberHistory); err != nil {
		return familyMemberHistory, err
	}
	return familyMemberHistory, nil
}
