// Copyright 2019 - 2022 The Samply Community
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir

import "encoding/json"

// THIS FILE IS GENERATED BY https://github.com/samply/golang-fhir-models
// PLEASE DO NOT EDIT BY HAND

// MessageDefinition is documented here http://hl7.org/fhir/StructureDefinition/MessageDefinition
type MessageDefinition struct {
	Id                      *string                            `bson:"id,omitempty" json:"id,omitempty"`
	IdElement               *PrimitiveElement                  `bson:"_id,omitempty" json:"_id,omitempty"`
	Meta                    *Meta                              `bson:"meta,omitempty" json:"meta,omitempty"`
	ImplicitRules           *string                            `bson:"implicitRules,omitempty" json:"implicitRules,omitempty"`
	ImplicitRulesElement    *PrimitiveElement                  `bson:"_implicitRules,omitempty" json:"_implicitRules,omitempty"`
	Language                *string                            `bson:"language,omitempty" json:"language,omitempty"`
	LanguageElement         *PrimitiveElement                  `bson:"_language,omitempty" json:"_language,omitempty"`
	Text                    *Narrative                         `bson:"text,omitempty" json:"text,omitempty"`
	Extension               []Extension                        `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension       []Extension                        `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Url                     *string                            `bson:"url,omitempty" json:"url,omitempty"`
	UrlElement              *PrimitiveElement                  `bson:"_url,omitempty" json:"_url,omitempty"`
	Identifier              []Identifier                       `bson:"identifier,omitempty" json:"identifier,omitempty"`
	Version                 *string                            `bson:"version,omitempty" json:"version,omitempty"`
	VersionElement          *PrimitiveElement                  `bson:"_version,omitempty" json:"_version,omitempty"`
	Name                    *string                            `bson:"name,omitempty" json:"name,omitempty"`
	NameElement             *PrimitiveElement                  `bson:"_name,omitempty" json:"_name,omitempty"`
	Title                   *string                            `bson:"title,omitempty" json:"title,omitempty"`
	TitleElement            *PrimitiveElement                  `bson:"_title,omitempty" json:"_title,omitempty"`
	Replaces                []string                           `bson:"replaces,omitempty" json:"replaces,omitempty"`
	ReplacesElement         []*PrimitiveElement                `bson:"_replaces,omitempty" json:"_replaces,omitempty"`
	Status                  PublicationStatus                  `bson:"status" json:"status"`
	StatusElement           *PrimitiveElement                  `bson:"_status,omitempty" json:"_status,omitempty"`
	Experimental            *bool                              `bson:"experimental,omitempty" json:"experimental,omitempty"`
	ExperimentalElement     *PrimitiveElement                  `bson:"_experimental,omitempty" json:"_experimental,omitempty"`
	Date                    string                             `bson:"date" json:"date"`
	DateElement             *PrimitiveElement                  `bson:"_date,omitempty" json:"_date,omitempty"`
	Publisher               *string                            `bson:"publisher,omitempty" json:"publisher,omitempty"`
	PublisherElement        *PrimitiveElement                  `bson:"_publisher,omitempty" json:"_publisher,omitempty"`
	Contact                 []ContactDetail                    `bson:"contact,omitempty" json:"contact,omitempty"`
	Description             *string                            `bson:"description,omitempty" json:"description,omitempty"`
	DescriptionElement      *PrimitiveElement                  `bson:"_description,omitempty" json:"_description,omitempty"`
	UseContext              []UsageContext                     `bson:"useContext,omitempty" json:"useContext,omitempty"`
	Jurisdiction            []CodeableConcept                  `bson:"jurisdiction,omitempty" json:"jurisdiction,omitempty"`
	Purpose                 *string                            `bson:"purpose,omitempty" json:"purpose,omitempty"`
	PurposeElement          *PrimitiveElement                  `bson:"_purpose,omitempty" json:"_purpose,omitempty"`
	Copyright               *string                            `bson:"copyright,omitempty" json:"copyright,omitempty"`
	CopyrightElement        *PrimitiveElement                  `bson:"_copyright,omitempty" json:"_copyright,omitempty"`
	Base                    *string                            `bson:"base,omitempty" json:"base,omitempty"`
	BaseElement             *PrimitiveElement                  `bson:"_base,omitempty" json:"_base,omitempty"`
	Parent                  []string                           `bson:"parent,omitempty" json:"parent,omitempty"`
	ParentElement           []*PrimitiveElement                `bson:"_parent,omitempty" json:"_parent,omitempty"`
	EventCoding             *Coding                            `bson:"eventCoding,omitempty" json:"eventCoding,omitempty"`
	EventUri                *string                            `bson:"eventUri,omitempty" json:"eventUri,omitempty"`
	EventUriElement         *PrimitiveElement                  `bson:"_eventUri,omitempty" json:"_eventUri,omitempty"`
	Category                *MessageSignificanceCategory       `bson:"category,omitempty" json:"category,omitempty"`
	CategoryElement         *PrimitiveElement                  `bson:"_category,omitempty" json:"_category,omitempty"`
	Focus                   []MessageDefinitionFocus           `bson:"focus,omitempty" json:"focus,omitempty"`
	ResponseRequired        *string                            `bson:"responseRequired,omitempty" json:"responseRequired,omitempty"`
	ResponseRequiredElement *PrimitiveElement                  `bson:"_responseRequired,omitempty" json:"_responseRequired,omitempty"`
	AllowedResponse         []MessageDefinitionAllowedResponse `bson:"allowedResponse,omitempty" json:"allowedResponse,omitempty"`
	Graph                   []string                           `bson:"graph,omitempty" json:"graph,omitempty"`
	GraphElement            []*PrimitiveElement                `bson:"_graph,omitempty" json:"_graph,omitempty"`
}
type MessageDefinitionFocus struct {
	Id                *string           `bson:"id,omitempty" json:"id,omitempty"`
	IdElement         *PrimitiveElement `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension         []Extension       `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension       `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Code              ResourceType      `bson:"code" json:"code"`
	CodeElement       *PrimitiveElement `bson:"_code,omitempty" json:"_code,omitempty"`
	Profile           *string           `bson:"profile,omitempty" json:"profile,omitempty"`
	ProfileElement    *PrimitiveElement `bson:"_profile,omitempty" json:"_profile,omitempty"`
	Min               int               `bson:"min" json:"min"`
	MinElement        *PrimitiveElement `bson:"_min,omitempty" json:"_min,omitempty"`
	Max               *string           `bson:"max,omitempty" json:"max,omitempty"`
	MaxElement        *PrimitiveElement `bson:"_max,omitempty" json:"_max,omitempty"`
}
type MessageDefinitionAllowedResponse struct {
	Id                *string           `bson:"id,omitempty" json:"id,omitempty"`
	IdElement         *PrimitiveElement `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension         []Extension       `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension       `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Message           string            `bson:"message" json:"message"`
	MessageElement    *PrimitiveElement `bson:"_message,omitempty" json:"_message,omitempty"`
	Situation         *string           `bson:"situation,omitempty" json:"situation,omitempty"`
	SituationElement  *PrimitiveElement `bson:"_situation,omitempty" json:"_situation,omitempty"`
}
type OtherMessageDefinition MessageDefinition

// MarshalJSON marshals the given MessageDefinition as JSON into a byte slice
func (r MessageDefinition) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		OtherMessageDefinition
		ResourceType string `json:"resourceType"`
	}{
		OtherMessageDefinition: OtherMessageDefinition(r),
		ResourceType:           "MessageDefinition",
	})
}

// UnmarshalMessageDefinition unmarshals a MessageDefinition.
func UnmarshalMessageDefinition(b []byte) (MessageDefinition, error) {
	var messageDefinition MessageDefinition
	if err := json.Unmarshal(b, &messageDefinition); err != nil {
		return messageDefinition, err
	}
	return messageDefinition, nil
}
