// Copyright 2019 - 2022 The Samply Community
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir

import "encoding/json"

// THIS FILE IS GENERATED BY https://github.com/samply/golang-fhir-models
// PLEASE DO NOT EDIT BY HAND

// MolecularSequence is documented here http://hl7.org/fhir/StructureDefinition/MolecularSequence
type MolecularSequence struct {
	Id                      *string                             `bson:"id,omitempty" json:"id,omitempty"`
	IdElement               *PrimitiveElement                   `bson:"_id,omitempty" json:"_id,omitempty"`
	Meta                    *Meta                               `bson:"meta,omitempty" json:"meta,omitempty"`
	ImplicitRules           *string                             `bson:"implicitRules,omitempty" json:"implicitRules,omitempty"`
	ImplicitRulesElement    *PrimitiveElement                   `bson:"_implicitRules,omitempty" json:"_implicitRules,omitempty"`
	Language                *string                             `bson:"language,omitempty" json:"language,omitempty"`
	LanguageElement         *PrimitiveElement                   `bson:"_language,omitempty" json:"_language,omitempty"`
	Text                    *Narrative                          `bson:"text,omitempty" json:"text,omitempty"`
	Extension               []Extension                         `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension       []Extension                         `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Identifier              []Identifier                        `bson:"identifier,omitempty" json:"identifier,omitempty"`
	Type                    *string                             `bson:"type,omitempty" json:"type,omitempty"`
	TypeElement             *PrimitiveElement                   `bson:"_type,omitempty" json:"_type,omitempty"`
	CoordinateSystem        int                                 `bson:"coordinateSystem" json:"coordinateSystem"`
	CoordinateSystemElement *PrimitiveElement                   `bson:"_coordinateSystem,omitempty" json:"_coordinateSystem,omitempty"`
	Patient                 *Reference                          `bson:"patient,omitempty" json:"patient,omitempty"`
	Specimen                *Reference                          `bson:"specimen,omitempty" json:"specimen,omitempty"`
	Device                  *Reference                          `bson:"device,omitempty" json:"device,omitempty"`
	Performer               *Reference                          `bson:"performer,omitempty" json:"performer,omitempty"`
	Quantity                *Quantity                           `bson:"quantity,omitempty" json:"quantity,omitempty"`
	ReferenceSeq            *MolecularSequenceReferenceSeq      `bson:"referenceSeq,omitempty" json:"referenceSeq,omitempty"`
	Variant                 []MolecularSequenceVariant          `bson:"variant,omitempty" json:"variant,omitempty"`
	ObservedSeq             *string                             `bson:"observedSeq,omitempty" json:"observedSeq,omitempty"`
	ObservedSeqElement      *PrimitiveElement                   `bson:"_observedSeq,omitempty" json:"_observedSeq,omitempty"`
	Quality                 []MolecularSequenceQuality          `bson:"quality,omitempty" json:"quality,omitempty"`
	ReadCoverage            *int                                `bson:"readCoverage,omitempty" json:"readCoverage,omitempty"`
	ReadCoverageElement     *PrimitiveElement                   `bson:"_readCoverage,omitempty" json:"_readCoverage,omitempty"`
	Repository              []MolecularSequenceRepository       `bson:"repository,omitempty" json:"repository,omitempty"`
	Pointer                 []Reference                         `bson:"pointer,omitempty" json:"pointer,omitempty"`
	StructureVariant        []MolecularSequenceStructureVariant `bson:"structureVariant,omitempty" json:"structureVariant,omitempty"`
}
type MolecularSequenceReferenceSeq struct {
	Id                        *string           `bson:"id,omitempty" json:"id,omitempty"`
	IdElement                 *PrimitiveElement `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension                 []Extension       `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension         []Extension       `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Chromosome                *CodeableConcept  `bson:"chromosome,omitempty" json:"chromosome,omitempty"`
	GenomeBuild               *string           `bson:"genomeBuild,omitempty" json:"genomeBuild,omitempty"`
	GenomeBuildElement        *PrimitiveElement `bson:"_genomeBuild,omitempty" json:"_genomeBuild,omitempty"`
	Orientation               *string           `bson:"orientation,omitempty" json:"orientation,omitempty"`
	OrientationElement        *PrimitiveElement `bson:"_orientation,omitempty" json:"_orientation,omitempty"`
	ReferenceSeqId            *CodeableConcept  `bson:"referenceSeqId,omitempty" json:"referenceSeqId,omitempty"`
	ReferenceSeqPointer       *Reference        `bson:"referenceSeqPointer,omitempty" json:"referenceSeqPointer,omitempty"`
	ReferenceSeqString        *string           `bson:"referenceSeqString,omitempty" json:"referenceSeqString,omitempty"`
	ReferenceSeqStringElement *PrimitiveElement `bson:"_referenceSeqString,omitempty" json:"_referenceSeqString,omitempty"`
	Strand                    *string           `bson:"strand,omitempty" json:"strand,omitempty"`
	StrandElement             *PrimitiveElement `bson:"_strand,omitempty" json:"_strand,omitempty"`
	WindowStart               *int              `bson:"windowStart,omitempty" json:"windowStart,omitempty"`
	WindowStartElement        *PrimitiveElement `bson:"_windowStart,omitempty" json:"_windowStart,omitempty"`
	WindowEnd                 *int              `bson:"windowEnd,omitempty" json:"windowEnd,omitempty"`
	WindowEndElement          *PrimitiveElement `bson:"_windowEnd,omitempty" json:"_windowEnd,omitempty"`
}
type MolecularSequenceVariant struct {
	Id                     *string           `bson:"id,omitempty" json:"id,omitempty"`
	IdElement              *PrimitiveElement `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension              []Extension       `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension      []Extension       `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Start                  *int              `bson:"start,omitempty" json:"start,omitempty"`
	StartElement           *PrimitiveElement `bson:"_start,omitempty" json:"_start,omitempty"`
	End                    *int              `bson:"end,omitempty" json:"end,omitempty"`
	EndElement             *PrimitiveElement `bson:"_end,omitempty" json:"_end,omitempty"`
	ObservedAllele         *string           `bson:"observedAllele,omitempty" json:"observedAllele,omitempty"`
	ObservedAlleleElement  *PrimitiveElement `bson:"_observedAllele,omitempty" json:"_observedAllele,omitempty"`
	ReferenceAllele        *string           `bson:"referenceAllele,omitempty" json:"referenceAllele,omitempty"`
	ReferenceAlleleElement *PrimitiveElement `bson:"_referenceAllele,omitempty" json:"_referenceAllele,omitempty"`
	Cigar                  *string           `bson:"cigar,omitempty" json:"cigar,omitempty"`
	CigarElement           *PrimitiveElement `bson:"_cigar,omitempty" json:"_cigar,omitempty"`
	VariantPointer         *Reference        `bson:"variantPointer,omitempty" json:"variantPointer,omitempty"`
}
type MolecularSequenceQuality struct {
	Id                *string                      `bson:"id,omitempty" json:"id,omitempty"`
	IdElement         *PrimitiveElement            `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension         []Extension                  `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension                  `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Type              string                       `bson:"type" json:"type"`
	TypeElement       *PrimitiveElement            `bson:"_type,omitempty" json:"_type,omitempty"`
	StandardSequence  *CodeableConcept             `bson:"standardSequence,omitempty" json:"standardSequence,omitempty"`
	Start             *int                         `bson:"start,omitempty" json:"start,omitempty"`
	StartElement      *PrimitiveElement            `bson:"_start,omitempty" json:"_start,omitempty"`
	End               *int                         `bson:"end,omitempty" json:"end,omitempty"`
	EndElement        *PrimitiveElement            `bson:"_end,omitempty" json:"_end,omitempty"`
	Score             *Quantity                    `bson:"score,omitempty" json:"score,omitempty"`
	Method            *CodeableConcept             `bson:"method,omitempty" json:"method,omitempty"`
	TruthTP           *json.Number                 `bson:"truthTP,omitempty" json:"truthTP,omitempty"`
	TruthTPElement    *PrimitiveElement            `bson:"_truthTP,omitempty" json:"_truthTP,omitempty"`
	QueryTP           *json.Number                 `bson:"queryTP,omitempty" json:"queryTP,omitempty"`
	QueryTPElement    *PrimitiveElement            `bson:"_queryTP,omitempty" json:"_queryTP,omitempty"`
	TruthFN           *json.Number                 `bson:"truthFN,omitempty" json:"truthFN,omitempty"`
	TruthFNElement    *PrimitiveElement            `bson:"_truthFN,omitempty" json:"_truthFN,omitempty"`
	QueryFP           *json.Number                 `bson:"queryFP,omitempty" json:"queryFP,omitempty"`
	QueryFPElement    *PrimitiveElement            `bson:"_queryFP,omitempty" json:"_queryFP,omitempty"`
	GtFP              *json.Number                 `bson:"gtFP,omitempty" json:"gtFP,omitempty"`
	GtFPElement       *PrimitiveElement            `bson:"_gtFP,omitempty" json:"_gtFP,omitempty"`
	Precision         *json.Number                 `bson:"precision,omitempty" json:"precision,omitempty"`
	PrecisionElement  *PrimitiveElement            `bson:"_precision,omitempty" json:"_precision,omitempty"`
	Recall            *json.Number                 `bson:"recall,omitempty" json:"recall,omitempty"`
	RecallElement     *PrimitiveElement            `bson:"_recall,omitempty" json:"_recall,omitempty"`
	FScore            *json.Number                 `bson:"fScore,omitempty" json:"fScore,omitempty"`
	FScoreElement     *PrimitiveElement            `bson:"_fScore,omitempty" json:"_fScore,omitempty"`
	Roc               *MolecularSequenceQualityRoc `bson:"roc,omitempty" json:"roc,omitempty"`
}
type MolecularSequenceQualityRoc struct {
	Id                 *string             `bson:"id,omitempty" json:"id,omitempty"`
	IdElement          *PrimitiveElement   `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension          []Extension         `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension  []Extension         `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Score              []int               `bson:"score,omitempty" json:"score,omitempty"`
	ScoreElement       []*PrimitiveElement `bson:"_score,omitempty" json:"_score,omitempty"`
	NumTP              []int               `bson:"numTP,omitempty" json:"numTP,omitempty"`
	NumTPElement       []*PrimitiveElement `bson:"_numTP,omitempty" json:"_numTP,omitempty"`
	NumFP              []int               `bson:"numFP,omitempty" json:"numFP,omitempty"`
	NumFPElement       []*PrimitiveElement `bson:"_numFP,omitempty" json:"_numFP,omitempty"`
	NumFN              []int               `bson:"numFN,omitempty" json:"numFN,omitempty"`
	NumFNElement       []*PrimitiveElement `bson:"_numFN,omitempty" json:"_numFN,omitempty"`
	Precision          []json.Number       `bson:"precision,omitempty" json:"precision,omitempty"`
	PrecisionElement   []*PrimitiveElement `bson:"_precision,omitempty" json:"_precision,omitempty"`
	Sensitivity        []json.Number       `bson:"sensitivity,omitempty" json:"sensitivity,omitempty"`
	SensitivityElement []*PrimitiveElement `bson:"_sensitivity,omitempty" json:"_sensitivity,omitempty"`
	FMeasure           []json.Number       `bson:"fMeasure,omitempty" json:"fMeasure,omitempty"`
	FMeasureElement    []*PrimitiveElement `bson:"_fMeasure,omitempty" json:"_fMeasure,omitempty"`
}
type MolecularSequenceRepository struct {
	Id                  *string           `bson:"id,omitempty" json:"id,omitempty"`
	IdElement           *PrimitiveElement `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension           []Extension       `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension   []Extension       `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Type                string            `bson:"type" json:"type"`
	TypeElement         *PrimitiveElement `bson:"_type,omitempty" json:"_type,omitempty"`
	Url                 *string           `bson:"url,omitempty" json:"url,omitempty"`
	UrlElement          *PrimitiveElement `bson:"_url,omitempty" json:"_url,omitempty"`
	Name                *string           `bson:"name,omitempty" json:"name,omitempty"`
	NameElement         *PrimitiveElement `bson:"_name,omitempty" json:"_name,omitempty"`
	DatasetId           *string           `bson:"datasetId,omitempty" json:"datasetId,omitempty"`
	DatasetIdElement    *PrimitiveElement `bson:"_datasetId,omitempty" json:"_datasetId,omitempty"`
	VariantsetId        *string           `bson:"variantsetId,omitempty" json:"variantsetId,omitempty"`
	VariantsetIdElement *PrimitiveElement `bson:"_variantsetId,omitempty" json:"_variantsetId,omitempty"`
	ReadsetId           *string           `bson:"readsetId,omitempty" json:"readsetId,omitempty"`
	ReadsetIdElement    *PrimitiveElement `bson:"_readsetId,omitempty" json:"_readsetId,omitempty"`
}
type MolecularSequenceStructureVariant struct {
	Id                *string                                 `bson:"id,omitempty" json:"id,omitempty"`
	IdElement         *PrimitiveElement                       `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension         []Extension                             `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension                             `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	VariantType       *CodeableConcept                        `bson:"variantType,omitempty" json:"variantType,omitempty"`
	Exact             *bool                                   `bson:"exact,omitempty" json:"exact,omitempty"`
	ExactElement      *PrimitiveElement                       `bson:"_exact,omitempty" json:"_exact,omitempty"`
	Length            *int                                    `bson:"length,omitempty" json:"length,omitempty"`
	LengthElement     *PrimitiveElement                       `bson:"_length,omitempty" json:"_length,omitempty"`
	Outer             *MolecularSequenceStructureVariantOuter `bson:"outer,omitempty" json:"outer,omitempty"`
	Inner             *MolecularSequenceStructureVariantInner `bson:"inner,omitempty" json:"inner,omitempty"`
}
type MolecularSequenceStructureVariantOuter struct {
	Id                *string           `bson:"id,omitempty" json:"id,omitempty"`
	IdElement         *PrimitiveElement `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension         []Extension       `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension       `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Start             *int              `bson:"start,omitempty" json:"start,omitempty"`
	StartElement      *PrimitiveElement `bson:"_start,omitempty" json:"_start,omitempty"`
	End               *int              `bson:"end,omitempty" json:"end,omitempty"`
	EndElement        *PrimitiveElement `bson:"_end,omitempty" json:"_end,omitempty"`
}
type MolecularSequenceStructureVariantInner struct {
	Id                *string           `bson:"id,omitempty" json:"id,omitempty"`
	IdElement         *PrimitiveElement `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension         []Extension       `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension       `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Start             *int              `bson:"start,omitempty" json:"start,omitempty"`
	StartElement      *PrimitiveElement `bson:"_start,omitempty" json:"_start,omitempty"`
	End               *int              `bson:"end,omitempty" json:"end,omitempty"`
	EndElement        *PrimitiveElement `bson:"_end,omitempty" json:"_end,omitempty"`
}
type OtherMolecularSequence MolecularSequence

// MarshalJSON marshals the given MolecularSequence as JSON into a byte slice
func (r MolecularSequence) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		OtherMolecularSequence
		ResourceType string `json:"resourceType"`
	}{
		OtherMolecularSequence: OtherMolecularSequence(r),
		ResourceType:           "MolecularSequence",
	})
}

// UnmarshalMolecularSequence unmarshals a MolecularSequence.
func UnmarshalMolecularSequence(b []byte) (MolecularSequence, error) {
	var molecularSequence MolecularSequence
	if err := json.Unmarshal(b, &molecularSequence); err != nil {
		return molecularSequence, err
	}
	return molecularSequence, nil
}
