// Copyright 2019 - 2022 The Samply Community
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir

import "encoding/json"

// THIS FILE IS GENERATED BY https://github.com/samply/golang-fhir-models
// PLEASE DO NOT EDIT BY HAND

// NamingSystem is documented here http://hl7.org/fhir/StructureDefinition/NamingSystem
type NamingSystem struct {
	Id                   *string                `bson:"id,omitempty" json:"id,omitempty"`
	IdElement            *PrimitiveElement      `bson:"_id,omitempty" json:"_id,omitempty"`
	Meta                 *Meta                  `bson:"meta,omitempty" json:"meta,omitempty"`
	ImplicitRules        *string                `bson:"implicitRules,omitempty" json:"implicitRules,omitempty"`
	ImplicitRulesElement *PrimitiveElement      `bson:"_implicitRules,omitempty" json:"_implicitRules,omitempty"`
	Language             *string                `bson:"language,omitempty" json:"language,omitempty"`
	LanguageElement      *PrimitiveElement      `bson:"_language,omitempty" json:"_language,omitempty"`
	Text                 *Narrative             `bson:"text,omitempty" json:"text,omitempty"`
	Extension            []Extension            `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension    []Extension            `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Name                 string                 `bson:"name" json:"name"`
	NameElement          *PrimitiveElement      `bson:"_name,omitempty" json:"_name,omitempty"`
	Status               PublicationStatus      `bson:"status" json:"status"`
	StatusElement        *PrimitiveElement      `bson:"_status,omitempty" json:"_status,omitempty"`
	Kind                 NamingSystemType       `bson:"kind" json:"kind"`
	KindElement          *PrimitiveElement      `bson:"_kind,omitempty" json:"_kind,omitempty"`
	Date                 string                 `bson:"date" json:"date"`
	DateElement          *PrimitiveElement      `bson:"_date,omitempty" json:"_date,omitempty"`
	Publisher            *string                `bson:"publisher,omitempty" json:"publisher,omitempty"`
	PublisherElement     *PrimitiveElement      `bson:"_publisher,omitempty" json:"_publisher,omitempty"`
	Contact              []ContactDetail        `bson:"contact,omitempty" json:"contact,omitempty"`
	Responsible          *string                `bson:"responsible,omitempty" json:"responsible,omitempty"`
	ResponsibleElement   *PrimitiveElement      `bson:"_responsible,omitempty" json:"_responsible,omitempty"`
	Type                 *CodeableConcept       `bson:"type,omitempty" json:"type,omitempty"`
	Description          *string                `bson:"description,omitempty" json:"description,omitempty"`
	DescriptionElement   *PrimitiveElement      `bson:"_description,omitempty" json:"_description,omitempty"`
	UseContext           []UsageContext         `bson:"useContext,omitempty" json:"useContext,omitempty"`
	Jurisdiction         []CodeableConcept      `bson:"jurisdiction,omitempty" json:"jurisdiction,omitempty"`
	Usage                *string                `bson:"usage,omitempty" json:"usage,omitempty"`
	UsageElement         *PrimitiveElement      `bson:"_usage,omitempty" json:"_usage,omitempty"`
	UniqueId             []NamingSystemUniqueId `bson:"uniqueId" json:"uniqueId"`
}
type NamingSystemUniqueId struct {
	Id                *string                    `bson:"id,omitempty" json:"id,omitempty"`
	IdElement         *PrimitiveElement          `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension         []Extension                `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension                `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Type              NamingSystemIdentifierType `bson:"type" json:"type"`
	TypeElement       *PrimitiveElement          `bson:"_type,omitempty" json:"_type,omitempty"`
	Value             string                     `bson:"value" json:"value"`
	ValueElement      *PrimitiveElement          `bson:"_value,omitempty" json:"_value,omitempty"`
	Preferred         *bool                      `bson:"preferred,omitempty" json:"preferred,omitempty"`
	PreferredElement  *PrimitiveElement          `bson:"_preferred,omitempty" json:"_preferred,omitempty"`
	Comment           *string                    `bson:"comment,omitempty" json:"comment,omitempty"`
	CommentElement    *PrimitiveElement          `bson:"_comment,omitempty" json:"_comment,omitempty"`
	Period            *Period                    `bson:"period,omitempty" json:"period,omitempty"`
}
type OtherNamingSystem NamingSystem

// MarshalJSON marshals the given NamingSystem as JSON into a byte slice
func (r NamingSystem) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		OtherNamingSystem
		ResourceType string `json:"resourceType"`
	}{
		OtherNamingSystem: OtherNamingSystem(r),
		ResourceType:      "NamingSystem",
	})
}

// UnmarshalNamingSystem unmarshals a NamingSystem.
func UnmarshalNamingSystem(b []byte) (NamingSystem, error) {
	var namingSystem NamingSystem
	if err := json.Unmarshal(b, &namingSystem); err != nil {
		return namingSystem, err
	}
	return namingSystem, nil
}
