// Copyright 2019 - 2022 The Samply Community
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir

import "encoding/json"

// THIS FILE IS GENERATED BY https://github.com/samply/golang-fhir-models
// PLEASE DO NOT EDIT BY HAND

// OperationDefinition is documented here http://hl7.org/fhir/StructureDefinition/OperationDefinition
type OperationDefinition struct {
	Id                   *string                        `bson:"id,omitempty" json:"id,omitempty"`
	IdElement            *PrimitiveElement              `bson:"_id,omitempty" json:"_id,omitempty"`
	Meta                 *Meta                          `bson:"meta,omitempty" json:"meta,omitempty"`
	ImplicitRules        *string                        `bson:"implicitRules,omitempty" json:"implicitRules,omitempty"`
	ImplicitRulesElement *PrimitiveElement              `bson:"_implicitRules,omitempty" json:"_implicitRules,omitempty"`
	Language             *string                        `bson:"language,omitempty" json:"language,omitempty"`
	LanguageElement      *PrimitiveElement              `bson:"_language,omitempty" json:"_language,omitempty"`
	Text                 *Narrative                     `bson:"text,omitempty" json:"text,omitempty"`
	Extension            []Extension                    `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension    []Extension                    `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Url                  *string                        `bson:"url,omitempty" json:"url,omitempty"`
	UrlElement           *PrimitiveElement              `bson:"_url,omitempty" json:"_url,omitempty"`
	Version              *string                        `bson:"version,omitempty" json:"version,omitempty"`
	VersionElement       *PrimitiveElement              `bson:"_version,omitempty" json:"_version,omitempty"`
	Name                 string                         `bson:"name" json:"name"`
	NameElement          *PrimitiveElement              `bson:"_name,omitempty" json:"_name,omitempty"`
	Title                *string                        `bson:"title,omitempty" json:"title,omitempty"`
	TitleElement         *PrimitiveElement              `bson:"_title,omitempty" json:"_title,omitempty"`
	Status               PublicationStatus              `bson:"status" json:"status"`
	StatusElement        *PrimitiveElement              `bson:"_status,omitempty" json:"_status,omitempty"`
	Kind                 OperationKind                  `bson:"kind" json:"kind"`
	KindElement          *PrimitiveElement              `bson:"_kind,omitempty" json:"_kind,omitempty"`
	Experimental         *bool                          `bson:"experimental,omitempty" json:"experimental,omitempty"`
	ExperimentalElement  *PrimitiveElement              `bson:"_experimental,omitempty" json:"_experimental,omitempty"`
	Date                 *string                        `bson:"date,omitempty" json:"date,omitempty"`
	DateElement          *PrimitiveElement              `bson:"_date,omitempty" json:"_date,omitempty"`
	Publisher            *string                        `bson:"publisher,omitempty" json:"publisher,omitempty"`
	PublisherElement     *PrimitiveElement              `bson:"_publisher,omitempty" json:"_publisher,omitempty"`
	Contact              []ContactDetail                `bson:"contact,omitempty" json:"contact,omitempty"`
	Description          *string                        `bson:"description,omitempty" json:"description,omitempty"`
	DescriptionElement   *PrimitiveElement              `bson:"_description,omitempty" json:"_description,omitempty"`
	UseContext           []UsageContext                 `bson:"useContext,omitempty" json:"useContext,omitempty"`
	Jurisdiction         []CodeableConcept              `bson:"jurisdiction,omitempty" json:"jurisdiction,omitempty"`
	Purpose              *string                        `bson:"purpose,omitempty" json:"purpose,omitempty"`
	PurposeElement       *PrimitiveElement              `bson:"_purpose,omitempty" json:"_purpose,omitempty"`
	AffectsState         *bool                          `bson:"affectsState,omitempty" json:"affectsState,omitempty"`
	AffectsStateElement  *PrimitiveElement              `bson:"_affectsState,omitempty" json:"_affectsState,omitempty"`
	Code                 string                         `bson:"code" json:"code"`
	CodeElement          *PrimitiveElement              `bson:"_code,omitempty" json:"_code,omitempty"`
	Comment              *string                        `bson:"comment,omitempty" json:"comment,omitempty"`
	CommentElement       *PrimitiveElement              `bson:"_comment,omitempty" json:"_comment,omitempty"`
	Base                 *string                        `bson:"base,omitempty" json:"base,omitempty"`
	BaseElement          *PrimitiveElement              `bson:"_base,omitempty" json:"_base,omitempty"`
	Resource             []ResourceType                 `bson:"resource,omitempty" json:"resource,omitempty"`
	ResourceElement      []*PrimitiveElement            `bson:"_resource,omitempty" json:"_resource,omitempty"`
	System               bool                           `bson:"system" json:"system"`
	SystemElement        *PrimitiveElement              `bson:"_system,omitempty" json:"_system,omitempty"`
	Type                 bool                           `bson:"type" json:"type"`
	TypeElement          *PrimitiveElement              `bson:"_type,omitempty" json:"_type,omitempty"`
	Instance             bool                           `bson:"instance" json:"instance"`
	InstanceElement      *PrimitiveElement              `bson:"_instance,omitempty" json:"_instance,omitempty"`
	InputProfile         *string                        `bson:"inputProfile,omitempty" json:"inputProfile,omitempty"`
	InputProfileElement  *PrimitiveElement              `bson:"_inputProfile,omitempty" json:"_inputProfile,omitempty"`
	OutputProfile        *string                        `bson:"outputProfile,omitempty" json:"outputProfile,omitempty"`
	OutputProfileElement *PrimitiveElement              `bson:"_outputProfile,omitempty" json:"_outputProfile,omitempty"`
	Parameter            []OperationDefinitionParameter `bson:"parameter,omitempty" json:"parameter,omitempty"`
	Overload             []OperationDefinitionOverload  `bson:"overload,omitempty" json:"overload,omitempty"`
}
type OperationDefinitionParameter struct {
	Id                   *string                                      `bson:"id,omitempty" json:"id,omitempty"`
	IdElement            *PrimitiveElement                            `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension            []Extension                                  `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension    []Extension                                  `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Name                 string                                       `bson:"name" json:"name"`
	NameElement          *PrimitiveElement                            `bson:"_name,omitempty" json:"_name,omitempty"`
	Use                  OperationParameterUse                        `bson:"use" json:"use"`
	UseElement           *PrimitiveElement                            `bson:"_use,omitempty" json:"_use,omitempty"`
	Min                  int                                          `bson:"min" json:"min"`
	MinElement           *PrimitiveElement                            `bson:"_min,omitempty" json:"_min,omitempty"`
	Max                  string                                       `bson:"max" json:"max"`
	MaxElement           *PrimitiveElement                            `bson:"_max,omitempty" json:"_max,omitempty"`
	Documentation        *string                                      `bson:"documentation,omitempty" json:"documentation,omitempty"`
	DocumentationElement *PrimitiveElement                            `bson:"_documentation,omitempty" json:"_documentation,omitempty"`
	Type                 *string                                      `bson:"type,omitempty" json:"type,omitempty"`
	TypeElement          *PrimitiveElement                            `bson:"_type,omitempty" json:"_type,omitempty"`
	TargetProfile        []string                                     `bson:"targetProfile,omitempty" json:"targetProfile,omitempty"`
	TargetProfileElement []*PrimitiveElement                          `bson:"_targetProfile,omitempty" json:"_targetProfile,omitempty"`
	SearchType           *SearchParamType                             `bson:"searchType,omitempty" json:"searchType,omitempty"`
	SearchTypeElement    *PrimitiveElement                            `bson:"_searchType,omitempty" json:"_searchType,omitempty"`
	Binding              *OperationDefinitionParameterBinding         `bson:"binding,omitempty" json:"binding,omitempty"`
	ReferencedFrom       []OperationDefinitionParameterReferencedFrom `bson:"referencedFrom,omitempty" json:"referencedFrom,omitempty"`
	Part                 []OperationDefinitionParameter               `bson:"part,omitempty" json:"part,omitempty"`
}
type OperationDefinitionParameterBinding struct {
	Id                *string           `bson:"id,omitempty" json:"id,omitempty"`
	IdElement         *PrimitiveElement `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension         []Extension       `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension       `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Strength          BindingStrength   `bson:"strength" json:"strength"`
	StrengthElement   *PrimitiveElement `bson:"_strength,omitempty" json:"_strength,omitempty"`
	ValueSet          string            `bson:"valueSet" json:"valueSet"`
	ValueSetElement   *PrimitiveElement `bson:"_valueSet,omitempty" json:"_valueSet,omitempty"`
}
type OperationDefinitionParameterReferencedFrom struct {
	Id                *string           `bson:"id,omitempty" json:"id,omitempty"`
	IdElement         *PrimitiveElement `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension         []Extension       `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension       `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Source            string            `bson:"source" json:"source"`
	SourceElement     *PrimitiveElement `bson:"_source,omitempty" json:"_source,omitempty"`
	SourceId          *string           `bson:"sourceId,omitempty" json:"sourceId,omitempty"`
	SourceIdElement   *PrimitiveElement `bson:"_sourceId,omitempty" json:"_sourceId,omitempty"`
}
type OperationDefinitionOverload struct {
	Id                   *string             `bson:"id,omitempty" json:"id,omitempty"`
	IdElement            *PrimitiveElement   `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension            []Extension         `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension    []Extension         `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	ParameterName        []string            `bson:"parameterName,omitempty" json:"parameterName,omitempty"`
	ParameterNameElement []*PrimitiveElement `bson:"_parameterName,omitempty" json:"_parameterName,omitempty"`
	Comment              *string             `bson:"comment,omitempty" json:"comment,omitempty"`
	CommentElement       *PrimitiveElement   `bson:"_comment,omitempty" json:"_comment,omitempty"`
}
type OtherOperationDefinition OperationDefinition

// MarshalJSON marshals the given OperationDefinition as JSON into a byte slice
func (r OperationDefinition) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		OtherOperationDefinition
		ResourceType string `json:"resourceType"`
	}{
		OtherOperationDefinition: OtherOperationDefinition(r),
		ResourceType:             "OperationDefinition",
	})
}

// UnmarshalOperationDefinition unmarshals a OperationDefinition.
func UnmarshalOperationDefinition(b []byte) (OperationDefinition, error) {
	var operationDefinition OperationDefinition
	if err := json.Unmarshal(b, &operationDefinition); err != nil {
		return operationDefinition, err
	}
	return operationDefinition, nil
}
