// Copyright 2019 - 2022 The Samply Community
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir

// THIS FILE IS GENERATED BY https://github.com/samply/golang-fhir-models
// PLEASE DO NOT EDIT BY HAND

// ParameterDefinition is documented here http://hl7.org/fhir/StructureDefinition/ParameterDefinition
type ParameterDefinition struct {
	Id                   *string               `bson:"id,omitempty" json:"id,omitempty"`
	IdElement            *PrimitiveElement     `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension            []Extension           `bson:"extension,omitempty" json:"extension,omitempty"`
	Name                 *string               `bson:"name,omitempty" json:"name,omitempty"`
	NameElement          *PrimitiveElement     `bson:"_name,omitempty" json:"_name,omitempty"`
	Use                  OperationParameterUse `bson:"use" json:"use"`
	UseElement           *PrimitiveElement     `bson:"_use,omitempty" json:"_use,omitempty"`
	Min                  *int                  `bson:"min,omitempty" json:"min,omitempty"`
	MinElement           *PrimitiveElement     `bson:"_min,omitempty" json:"_min,omitempty"`
	Max                  *string               `bson:"max,omitempty" json:"max,omitempty"`
	MaxElement           *PrimitiveElement     `bson:"_max,omitempty" json:"_max,omitempty"`
	Documentation        *string               `bson:"documentation,omitempty" json:"documentation,omitempty"`
	DocumentationElement *PrimitiveElement     `bson:"_documentation,omitempty" json:"_documentation,omitempty"`
	Type                 string                `bson:"type" json:"type"`
	TypeElement          *PrimitiveElement     `bson:"_type,omitempty" json:"_type,omitempty"`
	Profile              *string               `bson:"profile,omitempty" json:"profile,omitempty"`
	ProfileElement       *PrimitiveElement     `bson:"_profile,omitempty" json:"_profile,omitempty"`
}
