// Copyright 2019 - 2022 The Samply Community
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir

import "encoding/json"

// THIS FILE IS GENERATED BY https://github.com/samply/golang-fhir-models
// PLEASE DO NOT EDIT BY HAND

// Questionnaire is documented here http://hl7.org/fhir/StructureDefinition/Questionnaire
type Questionnaire struct {
	Id                    *string             `bson:"id,omitempty" json:"id,omitempty"`
	IdElement             *PrimitiveElement   `bson:"_id,omitempty" json:"_id,omitempty"`
	Meta                  *Meta               `bson:"meta,omitempty" json:"meta,omitempty"`
	ImplicitRules         *string             `bson:"implicitRules,omitempty" json:"implicitRules,omitempty"`
	ImplicitRulesElement  *PrimitiveElement   `bson:"_implicitRules,omitempty" json:"_implicitRules,omitempty"`
	Language              *string             `bson:"language,omitempty" json:"language,omitempty"`
	LanguageElement       *PrimitiveElement   `bson:"_language,omitempty" json:"_language,omitempty"`
	Text                  *Narrative          `bson:"text,omitempty" json:"text,omitempty"`
	Extension             []Extension         `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension     []Extension         `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Url                   *string             `bson:"url,omitempty" json:"url,omitempty"`
	UrlElement            *PrimitiveElement   `bson:"_url,omitempty" json:"_url,omitempty"`
	Identifier            []Identifier        `bson:"identifier,omitempty" json:"identifier,omitempty"`
	Version               *string             `bson:"version,omitempty" json:"version,omitempty"`
	VersionElement        *PrimitiveElement   `bson:"_version,omitempty" json:"_version,omitempty"`
	Name                  *string             `bson:"name,omitempty" json:"name,omitempty"`
	NameElement           *PrimitiveElement   `bson:"_name,omitempty" json:"_name,omitempty"`
	Title                 *string             `bson:"title,omitempty" json:"title,omitempty"`
	TitleElement          *PrimitiveElement   `bson:"_title,omitempty" json:"_title,omitempty"`
	DerivedFrom           []string            `bson:"derivedFrom,omitempty" json:"derivedFrom,omitempty"`
	DerivedFromElement    []*PrimitiveElement `bson:"_derivedFrom,omitempty" json:"_derivedFrom,omitempty"`
	Status                PublicationStatus   `bson:"status" json:"status"`
	StatusElement         *PrimitiveElement   `bson:"_status,omitempty" json:"_status,omitempty"`
	Experimental          *bool               `bson:"experimental,omitempty" json:"experimental,omitempty"`
	ExperimentalElement   *PrimitiveElement   `bson:"_experimental,omitempty" json:"_experimental,omitempty"`
	SubjectType           []ResourceType      `bson:"subjectType,omitempty" json:"subjectType,omitempty"`
	SubjectTypeElement    []*PrimitiveElement `bson:"_subjectType,omitempty" json:"_subjectType,omitempty"`
	Date                  *string             `bson:"date,omitempty" json:"date,omitempty"`
	DateElement           *PrimitiveElement   `bson:"_date,omitempty" json:"_date,omitempty"`
	Publisher             *string             `bson:"publisher,omitempty" json:"publisher,omitempty"`
	PublisherElement      *PrimitiveElement   `bson:"_publisher,omitempty" json:"_publisher,omitempty"`
	Contact               []ContactDetail     `bson:"contact,omitempty" json:"contact,omitempty"`
	Description           *string             `bson:"description,omitempty" json:"description,omitempty"`
	DescriptionElement    *PrimitiveElement   `bson:"_description,omitempty" json:"_description,omitempty"`
	UseContext            []UsageContext      `bson:"useContext,omitempty" json:"useContext,omitempty"`
	Jurisdiction          []CodeableConcept   `bson:"jurisdiction,omitempty" json:"jurisdiction,omitempty"`
	Purpose               *string             `bson:"purpose,omitempty" json:"purpose,omitempty"`
	PurposeElement        *PrimitiveElement   `bson:"_purpose,omitempty" json:"_purpose,omitempty"`
	Copyright             *string             `bson:"copyright,omitempty" json:"copyright,omitempty"`
	CopyrightElement      *PrimitiveElement   `bson:"_copyright,omitempty" json:"_copyright,omitempty"`
	ApprovalDate          *string             `bson:"approvalDate,omitempty" json:"approvalDate,omitempty"`
	ApprovalDateElement   *PrimitiveElement   `bson:"_approvalDate,omitempty" json:"_approvalDate,omitempty"`
	LastReviewDate        *string             `bson:"lastReviewDate,omitempty" json:"lastReviewDate,omitempty"`
	LastReviewDateElement *PrimitiveElement   `bson:"_lastReviewDate,omitempty" json:"_lastReviewDate,omitempty"`
	EffectivePeriod       *Period             `bson:"effectivePeriod,omitempty" json:"effectivePeriod,omitempty"`
	Code                  []Coding            `bson:"code,omitempty" json:"code,omitempty"`
	Item                  []QuestionnaireItem `bson:"item,omitempty" json:"item,omitempty"`
}
type QuestionnaireItem struct {
	Id                    *string                         `bson:"id,omitempty" json:"id,omitempty"`
	IdElement             *PrimitiveElement               `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension             []Extension                     `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension     []Extension                     `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	LinkId                string                          `bson:"linkId" json:"linkId"`
	LinkIdElement         *PrimitiveElement               `bson:"_linkId,omitempty" json:"_linkId,omitempty"`
	Definition            *string                         `bson:"definition,omitempty" json:"definition,omitempty"`
	DefinitionElement     *PrimitiveElement               `bson:"_definition,omitempty" json:"_definition,omitempty"`
	Code                  []Coding                        `bson:"code,omitempty" json:"code,omitempty"`
	Prefix                *string                         `bson:"prefix,omitempty" json:"prefix,omitempty"`
	PrefixElement         *PrimitiveElement               `bson:"_prefix,omitempty" json:"_prefix,omitempty"`
	Text                  *string                         `bson:"text,omitempty" json:"text,omitempty"`
	TextElement           *PrimitiveElement               `bson:"_text,omitempty" json:"_text,omitempty"`
	Type                  QuestionnaireItemType           `bson:"type" json:"type"`
	TypeElement           *PrimitiveElement               `bson:"_type,omitempty" json:"_type,omitempty"`
	EnableWhen            []QuestionnaireItemEnableWhen   `bson:"enableWhen,omitempty" json:"enableWhen,omitempty"`
	EnableBehavior        *EnableWhenBehavior             `bson:"enableBehavior,omitempty" json:"enableBehavior,omitempty"`
	EnableBehaviorElement *PrimitiveElement               `bson:"_enableBehavior,omitempty" json:"_enableBehavior,omitempty"`
	Required              *bool                           `bson:"required,omitempty" json:"required,omitempty"`
	RequiredElement       *PrimitiveElement               `bson:"_required,omitempty" json:"_required,omitempty"`
	Repeats               *bool                           `bson:"repeats,omitempty" json:"repeats,omitempty"`
	RepeatsElement        *PrimitiveElement               `bson:"_repeats,omitempty" json:"_repeats,omitempty"`
	ReadOnly              *bool                           `bson:"readOnly,omitempty" json:"readOnly,omitempty"`
	ReadOnlyElement       *PrimitiveElement               `bson:"_readOnly,omitempty" json:"_readOnly,omitempty"`
	MaxLength             *int                            `bson:"maxLength,omitempty" json:"maxLength,omitempty"`
	MaxLengthElement      *PrimitiveElement               `bson:"_maxLength,omitempty" json:"_maxLength,omitempty"`
	AnswerValueSet        *string                         `bson:"answerValueSet,omitempty" json:"answerValueSet,omitempty"`
	AnswerValueSetElement *PrimitiveElement               `bson:"_answerValueSet,omitempty" json:"_answerValueSet,omitempty"`
	AnswerOption          []QuestionnaireItemAnswerOption `bson:"answerOption,omitempty" json:"answerOption,omitempty"`
	Initial               []QuestionnaireItemInitial      `bson:"initial,omitempty" json:"initial,omitempty"`
	Item                  []QuestionnaireItem             `bson:"item,omitempty" json:"item,omitempty"`
}
type QuestionnaireItemEnableWhen struct {
	Id                    *string                   `bson:"id,omitempty" json:"id,omitempty"`
	IdElement             *PrimitiveElement         `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension             []Extension               `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension     []Extension               `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Question              string                    `bson:"question" json:"question"`
	QuestionElement       *PrimitiveElement         `bson:"_question,omitempty" json:"_question,omitempty"`
	Operator              QuestionnaireItemOperator `bson:"operator" json:"operator"`
	OperatorElement       *PrimitiveElement         `bson:"_operator,omitempty" json:"_operator,omitempty"`
	AnswerBoolean         *bool                     `bson:"answerBoolean,omitempty" json:"answerBoolean,omitempty"`
	AnswerBooleanElement  *PrimitiveElement         `bson:"_answerBoolean,omitempty" json:"_answerBoolean,omitempty"`
	AnswerDecimal         *json.Number              `bson:"answerDecimal,omitempty" json:"answerDecimal,omitempty"`
	AnswerDecimalElement  *PrimitiveElement         `bson:"_answerDecimal,omitempty" json:"_answerDecimal,omitempty"`
	AnswerInteger         *int                      `bson:"answerInteger,omitempty" json:"answerInteger,omitempty"`
	AnswerIntegerElement  *PrimitiveElement         `bson:"_answerInteger,omitempty" json:"_answerInteger,omitempty"`
	AnswerDate            *string                   `bson:"answerDate,omitempty" json:"answerDate,omitempty"`
	AnswerDateElement     *PrimitiveElement         `bson:"_answerDate,omitempty" json:"_answerDate,omitempty"`
	AnswerDateTime        *string                   `bson:"answerDateTime,omitempty" json:"answerDateTime,omitempty"`
	AnswerDateTimeElement *PrimitiveElement         `bson:"_answerDateTime,omitempty" json:"_answerDateTime,omitempty"`
	AnswerTime            *string                   `bson:"answerTime,omitempty" json:"answerTime,omitempty"`
	AnswerTimeElement     *PrimitiveElement         `bson:"_answerTime,omitempty" json:"_answerTime,omitempty"`
	AnswerString          *string                   `bson:"answerString,omitempty" json:"answerString,omitempty"`
	AnswerStringElement   *PrimitiveElement         `bson:"_answerString,omitempty" json:"_answerString,omitempty"`
	AnswerCoding          *Coding                   `bson:"answerCoding,omitempty" json:"answerCoding,omitempty"`
	AnswerQuantity        *Quantity                 `bson:"answerQuantity,omitempty" json:"answerQuantity,omitempty"`
	AnswerReference       *Reference                `bson:"answerReference,omitempty" json:"answerReference,omitempty"`
}
type QuestionnaireItemAnswerOption struct {
	Id                     *string           `bson:"id,omitempty" json:"id,omitempty"`
	IdElement              *PrimitiveElement `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension              []Extension       `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension      []Extension       `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	ValueInteger           *int              `bson:"valueInteger,omitempty" json:"valueInteger,omitempty"`
	ValueIntegerElement    *PrimitiveElement `bson:"_valueInteger,omitempty" json:"_valueInteger,omitempty"`
	ValueDate              *string           `bson:"valueDate,omitempty" json:"valueDate,omitempty"`
	ValueDateElement       *PrimitiveElement `bson:"_valueDate,omitempty" json:"_valueDate,omitempty"`
	ValueTime              *string           `bson:"valueTime,omitempty" json:"valueTime,omitempty"`
	ValueTimeElement       *PrimitiveElement `bson:"_valueTime,omitempty" json:"_valueTime,omitempty"`
	ValueString            *string           `bson:"valueString,omitempty" json:"valueString,omitempty"`
	ValueStringElement     *PrimitiveElement `bson:"_valueString,omitempty" json:"_valueString,omitempty"`
	ValueCoding            *Coding           `bson:"valueCoding,omitempty" json:"valueCoding,omitempty"`
	ValueReference         *Reference        `bson:"valueReference,omitempty" json:"valueReference,omitempty"`
	InitialSelected        *bool             `bson:"initialSelected,omitempty" json:"initialSelected,omitempty"`
	InitialSelectedElement *PrimitiveElement `bson:"_initialSelected,omitempty" json:"_initialSelected,omitempty"`
}
type QuestionnaireItemInitial struct {
	Id                   *string           `bson:"id,omitempty" json:"id,omitempty"`
	IdElement            *PrimitiveElement `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension            []Extension       `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension    []Extension       `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	ValueBoolean         *bool             `bson:"valueBoolean,omitempty" json:"valueBoolean,omitempty"`
	ValueBooleanElement  *PrimitiveElement `bson:"_valueBoolean,omitempty" json:"_valueBoolean,omitempty"`
	ValueDecimal         *json.Number      `bson:"valueDecimal,omitempty" json:"valueDecimal,omitempty"`
	ValueDecimalElement  *PrimitiveElement `bson:"_valueDecimal,omitempty" json:"_valueDecimal,omitempty"`
	ValueInteger         *int              `bson:"valueInteger,omitempty" json:"valueInteger,omitempty"`
	ValueIntegerElement  *PrimitiveElement `bson:"_valueInteger,omitempty" json:"_valueInteger,omitempty"`
	ValueDate            *string           `bson:"valueDate,omitempty" json:"valueDate,omitempty"`
	ValueDateElement     *PrimitiveElement `bson:"_valueDate,omitempty" json:"_valueDate,omitempty"`
	ValueDateTime        *string           `bson:"valueDateTime,omitempty" json:"valueDateTime,omitempty"`
	ValueDateTimeElement *PrimitiveElement `bson:"_valueDateTime,omitempty" json:"_valueDateTime,omitempty"`
	ValueTime            *string           `bson:"valueTime,omitempty" json:"valueTime,omitempty"`
	ValueTimeElement     *PrimitiveElement `bson:"_valueTime,omitempty" json:"_valueTime,omitempty"`
	ValueString          *string           `bson:"valueString,omitempty" json:"valueString,omitempty"`
	ValueStringElement   *PrimitiveElement `bson:"_valueString,omitempty" json:"_valueString,omitempty"`
	ValueUri             *string           `bson:"valueUri,omitempty" json:"valueUri,omitempty"`
	ValueUriElement      *PrimitiveElement `bson:"_valueUri,omitempty" json:"_valueUri,omitempty"`
	ValueAttachment      *Attachment       `bson:"valueAttachment,omitempty" json:"valueAttachment,omitempty"`
	ValueCoding          *Coding           `bson:"valueCoding,omitempty" json:"valueCoding,omitempty"`
	ValueQuantity        *Quantity         `bson:"valueQuantity,omitempty" json:"valueQuantity,omitempty"`
	ValueReference       *Reference        `bson:"valueReference,omitempty" json:"valueReference,omitempty"`
}
type OtherQuestionnaire Questionnaire

// MarshalJSON marshals the given Questionnaire as JSON into a byte slice
func (r Questionnaire) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		OtherQuestionnaire
		ResourceType string `json:"resourceType"`
	}{
		OtherQuestionnaire: OtherQuestionnaire(r),
		ResourceType:       "Questionnaire",
	})
}

// UnmarshalQuestionnaire unmarshals a Questionnaire.
func UnmarshalQuestionnaire(b []byte) (Questionnaire, error) {
	var questionnaire Questionnaire
	if err := json.Unmarshal(b, &questionnaire); err != nil {
		return questionnaire, err
	}
	return questionnaire, nil
}
