// Copyright 2019 - 2022 The Samply Community
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir

// THIS FILE IS GENERATED BY https://github.com/samply/golang-fhir-models
// PLEASE DO NOT EDIT BY HAND

// RelatedArtifact is documented here http://hl7.org/fhir/StructureDefinition/RelatedArtifact
type RelatedArtifact struct {
	Id              *string             `bson:"id,omitempty" json:"id,omitempty"`
	IdElement       *PrimitiveElement   `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension       []Extension         `bson:"extension,omitempty" json:"extension,omitempty"`
	Type            RelatedArtifactType `bson:"type" json:"type"`
	TypeElement     *PrimitiveElement   `bson:"_type,omitempty" json:"_type,omitempty"`
	Label           *string             `bson:"label,omitempty" json:"label,omitempty"`
	LabelElement    *PrimitiveElement   `bson:"_label,omitempty" json:"_label,omitempty"`
	Display         *string             `bson:"display,omitempty" json:"display,omitempty"`
	DisplayElement  *PrimitiveElement   `bson:"_display,omitempty" json:"_display,omitempty"`
	Citation        *string             `bson:"citation,omitempty" json:"citation,omitempty"`
	CitationElement *PrimitiveElement   `bson:"_citation,omitempty" json:"_citation,omitempty"`
	Url             *string             `bson:"url,omitempty" json:"url,omitempty"`
	UrlElement      *PrimitiveElement   `bson:"_url,omitempty" json:"_url,omitempty"`
	Document        *Attachment         `bson:"document,omitempty" json:"document,omitempty"`
	Resource        *string             `bson:"resource,omitempty" json:"resource,omitempty"`
	ResourceElement *PrimitiveElement   `bson:"_resource,omitempty" json:"_resource,omitempty"`
}
