// Copyright 2019 - 2022 The Samply Community
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir

import "encoding/json"

// THIS FILE IS GENERATED BY https://github.com/samply/golang-fhir-models
// PLEASE DO NOT EDIT BY HAND

// SearchParameter is documented here http://hl7.org/fhir/StructureDefinition/SearchParameter
type SearchParameter struct {
	Id                   *string                    `bson:"id,omitempty" json:"id,omitempty"`
	IdElement            *PrimitiveElement          `bson:"_id,omitempty" json:"_id,omitempty"`
	Meta                 *Meta                      `bson:"meta,omitempty" json:"meta,omitempty"`
	ImplicitRules        *string                    `bson:"implicitRules,omitempty" json:"implicitRules,omitempty"`
	ImplicitRulesElement *PrimitiveElement          `bson:"_implicitRules,omitempty" json:"_implicitRules,omitempty"`
	Language             *string                    `bson:"language,omitempty" json:"language,omitempty"`
	LanguageElement      *PrimitiveElement          `bson:"_language,omitempty" json:"_language,omitempty"`
	Text                 *Narrative                 `bson:"text,omitempty" json:"text,omitempty"`
	Extension            []Extension                `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension    []Extension                `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Url                  string                     `bson:"url" json:"url"`
	UrlElement           *PrimitiveElement          `bson:"_url,omitempty" json:"_url,omitempty"`
	Version              *string                    `bson:"version,omitempty" json:"version,omitempty"`
	VersionElement       *PrimitiveElement          `bson:"_version,omitempty" json:"_version,omitempty"`
	Name                 string                     `bson:"name" json:"name"`
	NameElement          *PrimitiveElement          `bson:"_name,omitempty" json:"_name,omitempty"`
	DerivedFrom          *string                    `bson:"derivedFrom,omitempty" json:"derivedFrom,omitempty"`
	DerivedFromElement   *PrimitiveElement          `bson:"_derivedFrom,omitempty" json:"_derivedFrom,omitempty"`
	Status               PublicationStatus          `bson:"status" json:"status"`
	StatusElement        *PrimitiveElement          `bson:"_status,omitempty" json:"_status,omitempty"`
	Experimental         *bool                      `bson:"experimental,omitempty" json:"experimental,omitempty"`
	ExperimentalElement  *PrimitiveElement          `bson:"_experimental,omitempty" json:"_experimental,omitempty"`
	Date                 *string                    `bson:"date,omitempty" json:"date,omitempty"`
	DateElement          *PrimitiveElement          `bson:"_date,omitempty" json:"_date,omitempty"`
	Publisher            *string                    `bson:"publisher,omitempty" json:"publisher,omitempty"`
	PublisherElement     *PrimitiveElement          `bson:"_publisher,omitempty" json:"_publisher,omitempty"`
	Contact              []ContactDetail            `bson:"contact,omitempty" json:"contact,omitempty"`
	Description          string                     `bson:"description" json:"description"`
	DescriptionElement   *PrimitiveElement          `bson:"_description,omitempty" json:"_description,omitempty"`
	UseContext           []UsageContext             `bson:"useContext,omitempty" json:"useContext,omitempty"`
	Jurisdiction         []CodeableConcept          `bson:"jurisdiction,omitempty" json:"jurisdiction,omitempty"`
	Purpose              *string                    `bson:"purpose,omitempty" json:"purpose,omitempty"`
	PurposeElement       *PrimitiveElement          `bson:"_purpose,omitempty" json:"_purpose,omitempty"`
	Code                 string                     `bson:"code" json:"code"`
	CodeElement          *PrimitiveElement          `bson:"_code,omitempty" json:"_code,omitempty"`
	Base                 []ResourceType             `bson:"base" json:"base"`
	BaseElement          []*PrimitiveElement        `bson:"_base,omitempty" json:"_base,omitempty"`
	Type                 SearchParamType            `bson:"type" json:"type"`
	TypeElement          *PrimitiveElement          `bson:"_type,omitempty" json:"_type,omitempty"`
	Expression           *string                    `bson:"expression,omitempty" json:"expression,omitempty"`
	ExpressionElement    *PrimitiveElement          `bson:"_expression,omitempty" json:"_expression,omitempty"`
	Xpath                *string                    `bson:"xpath,omitempty" json:"xpath,omitempty"`
	XpathElement         *PrimitiveElement          `bson:"_xpath,omitempty" json:"_xpath,omitempty"`
	XpathUsage           *XPathUsageType            `bson:"xpathUsage,omitempty" json:"xpathUsage,omitempty"`
	XpathUsageElement    *PrimitiveElement          `bson:"_xpathUsage,omitempty" json:"_xpathUsage,omitempty"`
	Target               []ResourceType             `bson:"target,omitempty" json:"target,omitempty"`
	TargetElement        []*PrimitiveElement        `bson:"_target,omitempty" json:"_target,omitempty"`
	MultipleOr           *bool                      `bson:"multipleOr,omitempty" json:"multipleOr,omitempty"`
	MultipleOrElement    *PrimitiveElement          `bson:"_multipleOr,omitempty" json:"_multipleOr,omitempty"`
	MultipleAnd          *bool                      `bson:"multipleAnd,omitempty" json:"multipleAnd,omitempty"`
	MultipleAndElement   *PrimitiveElement          `bson:"_multipleAnd,omitempty" json:"_multipleAnd,omitempty"`
	Comparator           []SearchComparator         `bson:"comparator,omitempty" json:"comparator,omitempty"`
	ComparatorElement    []*PrimitiveElement        `bson:"_comparator,omitempty" json:"_comparator,omitempty"`
	Modifier             []SearchModifierCode       `bson:"modifier,omitempty" json:"modifier,omitempty"`
	ModifierElement      []*PrimitiveElement        `bson:"_modifier,omitempty" json:"_modifier,omitempty"`
	Chain                []string                   `bson:"chain,omitempty" json:"chain,omitempty"`
	ChainElement         []*PrimitiveElement        `bson:"_chain,omitempty" json:"_chain,omitempty"`
	Component            []SearchParameterComponent `bson:"component,omitempty" json:"component,omitempty"`
}
type SearchParameterComponent struct {
	Id                *string           `bson:"id,omitempty" json:"id,omitempty"`
	IdElement         *PrimitiveElement `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension         []Extension       `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension       `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Definition        string            `bson:"definition" json:"definition"`
	DefinitionElement *PrimitiveElement `bson:"_definition,omitempty" json:"_definition,omitempty"`
	Expression        string            `bson:"expression" json:"expression"`
	ExpressionElement *PrimitiveElement `bson:"_expression,omitempty" json:"_expression,omitempty"`
}
type OtherSearchParameter SearchParameter

// MarshalJSON marshals the given SearchParameter as JSON into a byte slice
func (r SearchParameter) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		OtherSearchParameter
		ResourceType string `json:"resourceType"`
	}{
		OtherSearchParameter: OtherSearchParameter(r),
		ResourceType:         "SearchParameter",
	})
}

// UnmarshalSearchParameter unmarshals a SearchParameter.
func UnmarshalSearchParameter(b []byte) (SearchParameter, error) {
	var searchParameter SearchParameter
	if err := json.Unmarshal(b, &searchParameter); err != nil {
		return searchParameter, err
	}
	return searchParameter, nil
}
