// Copyright 2019 - 2022 The Samply Community
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir

import "encoding/json"

// THIS FILE IS GENERATED BY https://github.com/samply/golang-fhir-models
// PLEASE DO NOT EDIT BY HAND

// StructureDefinition is documented here http://hl7.org/fhir/StructureDefinition/StructureDefinition
type StructureDefinition struct {
	Id                      *string                          `bson:"id,omitempty" json:"id,omitempty"`
	IdElement               *PrimitiveElement                `bson:"_id,omitempty" json:"_id,omitempty"`
	Meta                    *Meta                            `bson:"meta,omitempty" json:"meta,omitempty"`
	ImplicitRules           *string                          `bson:"implicitRules,omitempty" json:"implicitRules,omitempty"`
	ImplicitRulesElement    *PrimitiveElement                `bson:"_implicitRules,omitempty" json:"_implicitRules,omitempty"`
	Language                *string                          `bson:"language,omitempty" json:"language,omitempty"`
	LanguageElement         *PrimitiveElement                `bson:"_language,omitempty" json:"_language,omitempty"`
	Text                    *Narrative                       `bson:"text,omitempty" json:"text,omitempty"`
	Extension               []Extension                      `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension       []Extension                      `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Url                     string                           `bson:"url" json:"url"`
	UrlElement              *PrimitiveElement                `bson:"_url,omitempty" json:"_url,omitempty"`
	Identifier              []Identifier                     `bson:"identifier,omitempty" json:"identifier,omitempty"`
	Version                 *string                          `bson:"version,omitempty" json:"version,omitempty"`
	VersionElement          *PrimitiveElement                `bson:"_version,omitempty" json:"_version,omitempty"`
	Name                    string                           `bson:"name" json:"name"`
	NameElement             *PrimitiveElement                `bson:"_name,omitempty" json:"_name,omitempty"`
	Title                   *string                          `bson:"title,omitempty" json:"title,omitempty"`
	TitleElement            *PrimitiveElement                `bson:"_title,omitempty" json:"_title,omitempty"`
	Status                  PublicationStatus                `bson:"status" json:"status"`
	StatusElement           *PrimitiveElement                `bson:"_status,omitempty" json:"_status,omitempty"`
	Experimental            *bool                            `bson:"experimental,omitempty" json:"experimental,omitempty"`
	ExperimentalElement     *PrimitiveElement                `bson:"_experimental,omitempty" json:"_experimental,omitempty"`
	Date                    *string                          `bson:"date,omitempty" json:"date,omitempty"`
	DateElement             *PrimitiveElement                `bson:"_date,omitempty" json:"_date,omitempty"`
	Publisher               *string                          `bson:"publisher,omitempty" json:"publisher,omitempty"`
	PublisherElement        *PrimitiveElement                `bson:"_publisher,omitempty" json:"_publisher,omitempty"`
	Contact                 []ContactDetail                  `bson:"contact,omitempty" json:"contact,omitempty"`
	Description             *string                          `bson:"description,omitempty" json:"description,omitempty"`
	DescriptionElement      *PrimitiveElement                `bson:"_description,omitempty" json:"_description,omitempty"`
	UseContext              []UsageContext                   `bson:"useContext,omitempty" json:"useContext,omitempty"`
	Jurisdiction            []CodeableConcept                `bson:"jurisdiction,omitempty" json:"jurisdiction,omitempty"`
	Purpose                 *string                          `bson:"purpose,omitempty" json:"purpose,omitempty"`
	PurposeElement          *PrimitiveElement                `bson:"_purpose,omitempty" json:"_purpose,omitempty"`
	Copyright               *string                          `bson:"copyright,omitempty" json:"copyright,omitempty"`
	CopyrightElement        *PrimitiveElement                `bson:"_copyright,omitempty" json:"_copyright,omitempty"`
	Keyword                 []Coding                         `bson:"keyword,omitempty" json:"keyword,omitempty"`
	FhirVersion             *FHIRVersion                     `bson:"fhirVersion,omitempty" json:"fhirVersion,omitempty"`
	FhirVersionElement      *PrimitiveElement                `bson:"_fhirVersion,omitempty" json:"_fhirVersion,omitempty"`
	Mapping                 []StructureDefinitionMapping     `bson:"mapping,omitempty" json:"mapping,omitempty"`
	Kind                    StructureDefinitionKind          `bson:"kind" json:"kind"`
	KindElement             *PrimitiveElement                `bson:"_kind,omitempty" json:"_kind,omitempty"`
	Abstract                bool                             `bson:"abstract" json:"abstract"`
	AbstractElement         *PrimitiveElement                `bson:"_abstract,omitempty" json:"_abstract,omitempty"`
	Context                 []StructureDefinitionContext     `bson:"context,omitempty" json:"context,omitempty"`
	ContextInvariant        []string                         `bson:"contextInvariant,omitempty" json:"contextInvariant,omitempty"`
	ContextInvariantElement []*PrimitiveElement              `bson:"_contextInvariant,omitempty" json:"_contextInvariant,omitempty"`
	Type                    string                           `bson:"type" json:"type"`
	TypeElement             *PrimitiveElement                `bson:"_type,omitempty" json:"_type,omitempty"`
	BaseDefinition          *string                          `bson:"baseDefinition,omitempty" json:"baseDefinition,omitempty"`
	BaseDefinitionElement   *PrimitiveElement                `bson:"_baseDefinition,omitempty" json:"_baseDefinition,omitempty"`
	Derivation              *TypeDerivationRule              `bson:"derivation,omitempty" json:"derivation,omitempty"`
	DerivationElement       *PrimitiveElement                `bson:"_derivation,omitempty" json:"_derivation,omitempty"`
	Snapshot                *StructureDefinitionSnapshot     `bson:"snapshot,omitempty" json:"snapshot,omitempty"`
	Differential            *StructureDefinitionDifferential `bson:"differential,omitempty" json:"differential,omitempty"`
}
type StructureDefinitionMapping struct {
	Id                *string           `bson:"id,omitempty" json:"id,omitempty"`
	IdElement         *PrimitiveElement `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension         []Extension       `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension       `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Identity          string            `bson:"identity" json:"identity"`
	IdentityElement   *PrimitiveElement `bson:"_identity,omitempty" json:"_identity,omitempty"`
	Uri               *string           `bson:"uri,omitempty" json:"uri,omitempty"`
	UriElement        *PrimitiveElement `bson:"_uri,omitempty" json:"_uri,omitempty"`
	Name              *string           `bson:"name,omitempty" json:"name,omitempty"`
	NameElement       *PrimitiveElement `bson:"_name,omitempty" json:"_name,omitempty"`
	Comment           *string           `bson:"comment,omitempty" json:"comment,omitempty"`
	CommentElement    *PrimitiveElement `bson:"_comment,omitempty" json:"_comment,omitempty"`
}
type StructureDefinitionContext struct {
	Id                *string              `bson:"id,omitempty" json:"id,omitempty"`
	IdElement         *PrimitiveElement    `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension         []Extension          `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension          `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Type              ExtensionContextType `bson:"type" json:"type"`
	TypeElement       *PrimitiveElement    `bson:"_type,omitempty" json:"_type,omitempty"`
	Expression        string               `bson:"expression" json:"expression"`
	ExpressionElement *PrimitiveElement    `bson:"_expression,omitempty" json:"_expression,omitempty"`
}
type StructureDefinitionSnapshot struct {
	Id                *string             `bson:"id,omitempty" json:"id,omitempty"`
	IdElement         *PrimitiveElement   `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension         []Extension         `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension         `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Element           []ElementDefinition `bson:"element" json:"element"`
}
type StructureDefinitionDifferential struct {
	Id                *string             `bson:"id,omitempty" json:"id,omitempty"`
	IdElement         *PrimitiveElement   `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension         []Extension         `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension         `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Element           []ElementDefinition `bson:"element" json:"element"`
}
type OtherStructureDefinition StructureDefinition

// MarshalJSON marshals the given StructureDefinition as JSON into a byte slice
func (r StructureDefinition) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		OtherStructureDefinition
		ResourceType string `json:"resourceType"`
	}{
		OtherStructureDefinition: OtherStructureDefinition(r),
		ResourceType:             "StructureDefinition",
	})
}

// UnmarshalStructureDefinition unmarshals a StructureDefinition.
func UnmarshalStructureDefinition(b []byte) (StructureDefinition, error) {
	var structureDefinition StructureDefinition
	if err := json.Unmarshal(b, &structureDefinition); err != nil {
		return structureDefinition, err
	}
	return structureDefinition, nil
}
