// Copyright 2019 - 2022 The Samply Community
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir

import "encoding/json"

// THIS FILE IS GENERATED BY https://github.com/samply/golang-fhir-models
// PLEASE DO NOT EDIT BY HAND

// TerminologyCapabilities is documented here http://hl7.org/fhir/StructureDefinition/TerminologyCapabilities
type TerminologyCapabilities struct {
	Id                   *string                                `bson:"id,omitempty" json:"id,omitempty"`
	IdElement            *PrimitiveElement                      `bson:"_id,omitempty" json:"_id,omitempty"`
	Meta                 *Meta                                  `bson:"meta,omitempty" json:"meta,omitempty"`
	ImplicitRules        *string                                `bson:"implicitRules,omitempty" json:"implicitRules,omitempty"`
	ImplicitRulesElement *PrimitiveElement                      `bson:"_implicitRules,omitempty" json:"_implicitRules,omitempty"`
	Language             *string                                `bson:"language,omitempty" json:"language,omitempty"`
	LanguageElement      *PrimitiveElement                      `bson:"_language,omitempty" json:"_language,omitempty"`
	Text                 *Narrative                             `bson:"text,omitempty" json:"text,omitempty"`
	Extension            []Extension                            `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension    []Extension                            `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Url                  *string                                `bson:"url,omitempty" json:"url,omitempty"`
	UrlElement           *PrimitiveElement                      `bson:"_url,omitempty" json:"_url,omitempty"`
	Version              *string                                `bson:"version,omitempty" json:"version,omitempty"`
	VersionElement       *PrimitiveElement                      `bson:"_version,omitempty" json:"_version,omitempty"`
	Name                 *string                                `bson:"name,omitempty" json:"name,omitempty"`
	NameElement          *PrimitiveElement                      `bson:"_name,omitempty" json:"_name,omitempty"`
	Title                *string                                `bson:"title,omitempty" json:"title,omitempty"`
	TitleElement         *PrimitiveElement                      `bson:"_title,omitempty" json:"_title,omitempty"`
	Status               PublicationStatus                      `bson:"status" json:"status"`
	StatusElement        *PrimitiveElement                      `bson:"_status,omitempty" json:"_status,omitempty"`
	Experimental         *bool                                  `bson:"experimental,omitempty" json:"experimental,omitempty"`
	ExperimentalElement  *PrimitiveElement                      `bson:"_experimental,omitempty" json:"_experimental,omitempty"`
	Date                 string                                 `bson:"date" json:"date"`
	DateElement          *PrimitiveElement                      `bson:"_date,omitempty" json:"_date,omitempty"`
	Publisher            *string                                `bson:"publisher,omitempty" json:"publisher,omitempty"`
	PublisherElement     *PrimitiveElement                      `bson:"_publisher,omitempty" json:"_publisher,omitempty"`
	Contact              []ContactDetail                        `bson:"contact,omitempty" json:"contact,omitempty"`
	Description          *string                                `bson:"description,omitempty" json:"description,omitempty"`
	DescriptionElement   *PrimitiveElement                      `bson:"_description,omitempty" json:"_description,omitempty"`
	UseContext           []UsageContext                         `bson:"useContext,omitempty" json:"useContext,omitempty"`
	Jurisdiction         []CodeableConcept                      `bson:"jurisdiction,omitempty" json:"jurisdiction,omitempty"`
	Purpose              *string                                `bson:"purpose,omitempty" json:"purpose,omitempty"`
	PurposeElement       *PrimitiveElement                      `bson:"_purpose,omitempty" json:"_purpose,omitempty"`
	Copyright            *string                                `bson:"copyright,omitempty" json:"copyright,omitempty"`
	CopyrightElement     *PrimitiveElement                      `bson:"_copyright,omitempty" json:"_copyright,omitempty"`
	Kind                 CapabilityStatementKind                `bson:"kind" json:"kind"`
	KindElement          *PrimitiveElement                      `bson:"_kind,omitempty" json:"_kind,omitempty"`
	Software             *TerminologyCapabilitiesSoftware       `bson:"software,omitempty" json:"software,omitempty"`
	Implementation       *TerminologyCapabilitiesImplementation `bson:"implementation,omitempty" json:"implementation,omitempty"`
	LockedDate           *bool                                  `bson:"lockedDate,omitempty" json:"lockedDate,omitempty"`
	LockedDateElement    *PrimitiveElement                      `bson:"_lockedDate,omitempty" json:"_lockedDate,omitempty"`
	CodeSystem           []TerminologyCapabilitiesCodeSystem    `bson:"codeSystem,omitempty" json:"codeSystem,omitempty"`
	Expansion            *TerminologyCapabilitiesExpansion      `bson:"expansion,omitempty" json:"expansion,omitempty"`
	CodeSearch           *CodeSearchSupport                     `bson:"codeSearch,omitempty" json:"codeSearch,omitempty"`
	CodeSearchElement    *PrimitiveElement                      `bson:"_codeSearch,omitempty" json:"_codeSearch,omitempty"`
	ValidateCode         *TerminologyCapabilitiesValidateCode   `bson:"validateCode,omitempty" json:"validateCode,omitempty"`
	Translation          *TerminologyCapabilitiesTranslation    `bson:"translation,omitempty" json:"translation,omitempty"`
	Closure              *TerminologyCapabilitiesClosure        `bson:"closure,omitempty" json:"closure,omitempty"`
}
type TerminologyCapabilitiesSoftware struct {
	Id                *string           `bson:"id,omitempty" json:"id,omitempty"`
	IdElement         *PrimitiveElement `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension         []Extension       `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension       `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Name              string            `bson:"name" json:"name"`
	NameElement       *PrimitiveElement `bson:"_name,omitempty" json:"_name,omitempty"`
	Version           *string           `bson:"version,omitempty" json:"version,omitempty"`
	VersionElement    *PrimitiveElement `bson:"_version,omitempty" json:"_version,omitempty"`
}
type TerminologyCapabilitiesImplementation struct {
	Id                 *string           `bson:"id,omitempty" json:"id,omitempty"`
	IdElement          *PrimitiveElement `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension          []Extension       `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension  []Extension       `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Description        string            `bson:"description" json:"description"`
	DescriptionElement *PrimitiveElement `bson:"_description,omitempty" json:"_description,omitempty"`
	Url                *string           `bson:"url,omitempty" json:"url,omitempty"`
	UrlElement         *PrimitiveElement `bson:"_url,omitempty" json:"_url,omitempty"`
}
type TerminologyCapabilitiesCodeSystem struct {
	Id                 *string                                    `bson:"id,omitempty" json:"id,omitempty"`
	IdElement          *PrimitiveElement                          `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension          []Extension                                `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension  []Extension                                `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Uri                *string                                    `bson:"uri,omitempty" json:"uri,omitempty"`
	UriElement         *PrimitiveElement                          `bson:"_uri,omitempty" json:"_uri,omitempty"`
	Version            []TerminologyCapabilitiesCodeSystemVersion `bson:"version,omitempty" json:"version,omitempty"`
	Subsumption        *bool                                      `bson:"subsumption,omitempty" json:"subsumption,omitempty"`
	SubsumptionElement *PrimitiveElement                          `bson:"_subsumption,omitempty" json:"_subsumption,omitempty"`
}
type TerminologyCapabilitiesCodeSystemVersion struct {
	Id                   *string                                          `bson:"id,omitempty" json:"id,omitempty"`
	IdElement            *PrimitiveElement                                `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension            []Extension                                      `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension    []Extension                                      `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Code                 *string                                          `bson:"code,omitempty" json:"code,omitempty"`
	CodeElement          *PrimitiveElement                                `bson:"_code,omitempty" json:"_code,omitempty"`
	IsDefault            *bool                                            `bson:"isDefault,omitempty" json:"isDefault,omitempty"`
	IsDefaultElement     *PrimitiveElement                                `bson:"_isDefault,omitempty" json:"_isDefault,omitempty"`
	Compositional        *bool                                            `bson:"compositional,omitempty" json:"compositional,omitempty"`
	CompositionalElement *PrimitiveElement                                `bson:"_compositional,omitempty" json:"_compositional,omitempty"`
	Language             []string                                         `bson:"language,omitempty" json:"language,omitempty"`
	LanguageElement      []*PrimitiveElement                              `bson:"_language,omitempty" json:"_language,omitempty"`
	Filter               []TerminologyCapabilitiesCodeSystemVersionFilter `bson:"filter,omitempty" json:"filter,omitempty"`
	Property             []string                                         `bson:"property,omitempty" json:"property,omitempty"`
	PropertyElement      []*PrimitiveElement                              `bson:"_property,omitempty" json:"_property,omitempty"`
}
type TerminologyCapabilitiesCodeSystemVersionFilter struct {
	Id                *string             `bson:"id,omitempty" json:"id,omitempty"`
	IdElement         *PrimitiveElement   `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension         []Extension         `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension         `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Code              string              `bson:"code" json:"code"`
	CodeElement       *PrimitiveElement   `bson:"_code,omitempty" json:"_code,omitempty"`
	Op                []string            `bson:"op" json:"op"`
	OpElement         []*PrimitiveElement `bson:"_op,omitempty" json:"_op,omitempty"`
}
type TerminologyCapabilitiesExpansion struct {
	Id                  *string                                     `bson:"id,omitempty" json:"id,omitempty"`
	IdElement           *PrimitiveElement                           `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension           []Extension                                 `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension   []Extension                                 `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Hierarchical        *bool                                       `bson:"hierarchical,omitempty" json:"hierarchical,omitempty"`
	HierarchicalElement *PrimitiveElement                           `bson:"_hierarchical,omitempty" json:"_hierarchical,omitempty"`
	Paging              *bool                                       `bson:"paging,omitempty" json:"paging,omitempty"`
	PagingElement       *PrimitiveElement                           `bson:"_paging,omitempty" json:"_paging,omitempty"`
	Incomplete          *bool                                       `bson:"incomplete,omitempty" json:"incomplete,omitempty"`
	IncompleteElement   *PrimitiveElement                           `bson:"_incomplete,omitempty" json:"_incomplete,omitempty"`
	Parameter           []TerminologyCapabilitiesExpansionParameter `bson:"parameter,omitempty" json:"parameter,omitempty"`
	TextFilter          *string                                     `bson:"textFilter,omitempty" json:"textFilter,omitempty"`
	TextFilterElement   *PrimitiveElement                           `bson:"_textFilter,omitempty" json:"_textFilter,omitempty"`
}
type TerminologyCapabilitiesExpansionParameter struct {
	Id                   *string           `bson:"id,omitempty" json:"id,omitempty"`
	IdElement            *PrimitiveElement `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension            []Extension       `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension    []Extension       `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Name                 string            `bson:"name" json:"name"`
	NameElement          *PrimitiveElement `bson:"_name,omitempty" json:"_name,omitempty"`
	Documentation        *string           `bson:"documentation,omitempty" json:"documentation,omitempty"`
	DocumentationElement *PrimitiveElement `bson:"_documentation,omitempty" json:"_documentation,omitempty"`
}
type TerminologyCapabilitiesValidateCode struct {
	Id                  *string           `bson:"id,omitempty" json:"id,omitempty"`
	IdElement           *PrimitiveElement `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension           []Extension       `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension   []Extension       `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Translations        bool              `bson:"translations" json:"translations"`
	TranslationsElement *PrimitiveElement `bson:"_translations,omitempty" json:"_translations,omitempty"`
}
type TerminologyCapabilitiesTranslation struct {
	Id                *string           `bson:"id,omitempty" json:"id,omitempty"`
	IdElement         *PrimitiveElement `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension         []Extension       `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension       `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	NeedsMap          bool              `bson:"needsMap" json:"needsMap"`
	NeedsMapElement   *PrimitiveElement `bson:"_needsMap,omitempty" json:"_needsMap,omitempty"`
}
type TerminologyCapabilitiesClosure struct {
	Id                 *string           `bson:"id,omitempty" json:"id,omitempty"`
	IdElement          *PrimitiveElement `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension          []Extension       `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension  []Extension       `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Translation        *bool             `bson:"translation,omitempty" json:"translation,omitempty"`
	TranslationElement *PrimitiveElement `bson:"_translation,omitempty" json:"_translation,omitempty"`
}
type OtherTerminologyCapabilities TerminologyCapabilities

// MarshalJSON marshals the given TerminologyCapabilities as JSON into a byte slice
func (r TerminologyCapabilities) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		OtherTerminologyCapabilities
		ResourceType string `json:"resourceType"`
	}{
		OtherTerminologyCapabilities: OtherTerminologyCapabilities(r),
		ResourceType:                 "TerminologyCapabilities",
	})
}

// UnmarshalTerminologyCapabilities unmarshals a TerminologyCapabilities.
func UnmarshalTerminologyCapabilities(b []byte) (TerminologyCapabilities, error) {
	var terminologyCapabilities TerminologyCapabilities
	if err := json.Unmarshal(b, &terminologyCapabilities); err != nil {
		return terminologyCapabilities, err
	}
	return terminologyCapabilities, nil
}
