// Copyright 2019 - 2022 The Samply Community
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir

import "encoding/json"

// THIS FILE IS GENERATED BY https://github.com/samply/golang-fhir-models
// PLEASE DO NOT EDIT BY HAND

// ValueSet is documented here http://hl7.org/fhir/StructureDefinition/ValueSet
type ValueSet struct {
	Id                   *string            `bson:"id,omitempty" json:"id,omitempty"`
	IdElement            *PrimitiveElement  `bson:"_id,omitempty" json:"_id,omitempty"`
	Meta                 *Meta              `bson:"meta,omitempty" json:"meta,omitempty"`
	ImplicitRules        *string            `bson:"implicitRules,omitempty" json:"implicitRules,omitempty"`
	ImplicitRulesElement *PrimitiveElement  `bson:"_implicitRules,omitempty" json:"_implicitRules,omitempty"`
	Language             *string            `bson:"language,omitempty" json:"language,omitempty"`
	LanguageElement      *PrimitiveElement  `bson:"_language,omitempty" json:"_language,omitempty"`
	Text                 *Narrative         `bson:"text,omitempty" json:"text,omitempty"`
	Extension            []Extension        `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension    []Extension        `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Url                  *string            `bson:"url,omitempty" json:"url,omitempty"`
	UrlElement           *PrimitiveElement  `bson:"_url,omitempty" json:"_url,omitempty"`
	Identifier           []Identifier       `bson:"identifier,omitempty" json:"identifier,omitempty"`
	Version              *string            `bson:"version,omitempty" json:"version,omitempty"`
	VersionElement       *PrimitiveElement  `bson:"_version,omitempty" json:"_version,omitempty"`
	Name                 *string            `bson:"name,omitempty" json:"name,omitempty"`
	NameElement          *PrimitiveElement  `bson:"_name,omitempty" json:"_name,omitempty"`
	Title                *string            `bson:"title,omitempty" json:"title,omitempty"`
	TitleElement         *PrimitiveElement  `bson:"_title,omitempty" json:"_title,omitempty"`
	Status               PublicationStatus  `bson:"status" json:"status"`
	StatusElement        *PrimitiveElement  `bson:"_status,omitempty" json:"_status,omitempty"`
	Experimental         *bool              `bson:"experimental,omitempty" json:"experimental,omitempty"`
	ExperimentalElement  *PrimitiveElement  `bson:"_experimental,omitempty" json:"_experimental,omitempty"`
	Date                 *string            `bson:"date,omitempty" json:"date,omitempty"`
	DateElement          *PrimitiveElement  `bson:"_date,omitempty" json:"_date,omitempty"`
	Publisher            *string            `bson:"publisher,omitempty" json:"publisher,omitempty"`
	PublisherElement     *PrimitiveElement  `bson:"_publisher,omitempty" json:"_publisher,omitempty"`
	Contact              []ContactDetail    `bson:"contact,omitempty" json:"contact,omitempty"`
	Description          *string            `bson:"description,omitempty" json:"description,omitempty"`
	DescriptionElement   *PrimitiveElement  `bson:"_description,omitempty" json:"_description,omitempty"`
	UseContext           []UsageContext     `bson:"useContext,omitempty" json:"useContext,omitempty"`
	Jurisdiction         []CodeableConcept  `bson:"jurisdiction,omitempty" json:"jurisdiction,omitempty"`
	Immutable            *bool              `bson:"immutable,omitempty" json:"immutable,omitempty"`
	ImmutableElement     *PrimitiveElement  `bson:"_immutable,omitempty" json:"_immutable,omitempty"`
	Purpose              *string            `bson:"purpose,omitempty" json:"purpose,omitempty"`
	PurposeElement       *PrimitiveElement  `bson:"_purpose,omitempty" json:"_purpose,omitempty"`
	Copyright            *string            `bson:"copyright,omitempty" json:"copyright,omitempty"`
	CopyrightElement     *PrimitiveElement  `bson:"_copyright,omitempty" json:"_copyright,omitempty"`
	Compose              *ValueSetCompose   `bson:"compose,omitempty" json:"compose,omitempty"`
	Expansion            *ValueSetExpansion `bson:"expansion,omitempty" json:"expansion,omitempty"`
}
type ValueSetCompose struct {
	Id                *string                  `bson:"id,omitempty" json:"id,omitempty"`
	IdElement         *PrimitiveElement        `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension         []Extension              `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension              `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	LockedDate        *string                  `bson:"lockedDate,omitempty" json:"lockedDate,omitempty"`
	LockedDateElement *PrimitiveElement        `bson:"_lockedDate,omitempty" json:"_lockedDate,omitempty"`
	Inactive          *bool                    `bson:"inactive,omitempty" json:"inactive,omitempty"`
	InactiveElement   *PrimitiveElement        `bson:"_inactive,omitempty" json:"_inactive,omitempty"`
	Include           []ValueSetComposeInclude `bson:"include" json:"include"`
	Exclude           []ValueSetComposeInclude `bson:"exclude,omitempty" json:"exclude,omitempty"`
}
type ValueSetComposeInclude struct {
	Id                *string                         `bson:"id,omitempty" json:"id,omitempty"`
	IdElement         *PrimitiveElement               `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension         []Extension                     `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension                     `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	System            *string                         `bson:"system,omitempty" json:"system,omitempty"`
	SystemElement     *PrimitiveElement               `bson:"_system,omitempty" json:"_system,omitempty"`
	Version           *string                         `bson:"version,omitempty" json:"version,omitempty"`
	VersionElement    *PrimitiveElement               `bson:"_version,omitempty" json:"_version,omitempty"`
	Concept           []ValueSetComposeIncludeConcept `bson:"concept,omitempty" json:"concept,omitempty"`
	Filter            []ValueSetComposeIncludeFilter  `bson:"filter,omitempty" json:"filter,omitempty"`
	ValueSet          []string                        `bson:"valueSet,omitempty" json:"valueSet,omitempty"`
	ValueSetElement   []*PrimitiveElement             `bson:"_valueSet,omitempty" json:"_valueSet,omitempty"`
}
type ValueSetComposeIncludeConcept struct {
	Id                *string                                    `bson:"id,omitempty" json:"id,omitempty"`
	IdElement         *PrimitiveElement                          `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension         []Extension                                `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension                                `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Code              string                                     `bson:"code" json:"code"`
	CodeElement       *PrimitiveElement                          `bson:"_code,omitempty" json:"_code,omitempty"`
	Display           *string                                    `bson:"display,omitempty" json:"display,omitempty"`
	DisplayElement    *PrimitiveElement                          `bson:"_display,omitempty" json:"_display,omitempty"`
	Designation       []ValueSetComposeIncludeConceptDesignation `bson:"designation,omitempty" json:"designation,omitempty"`
}
type ValueSetComposeIncludeConceptDesignation struct {
	Id                *string           `bson:"id,omitempty" json:"id,omitempty"`
	IdElement         *PrimitiveElement `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension         []Extension       `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension       `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Language          *string           `bson:"language,omitempty" json:"language,omitempty"`
	LanguageElement   *PrimitiveElement `bson:"_language,omitempty" json:"_language,omitempty"`
	Use               *Coding           `bson:"use,omitempty" json:"use,omitempty"`
	Value             string            `bson:"value" json:"value"`
	ValueElement      *PrimitiveElement `bson:"_value,omitempty" json:"_value,omitempty"`
}
type ValueSetComposeIncludeFilter struct {
	Id                *string           `bson:"id,omitempty" json:"id,omitempty"`
	IdElement         *PrimitiveElement `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension         []Extension       `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension       `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Property          string            `bson:"property" json:"property"`
	PropertyElement   *PrimitiveElement `bson:"_property,omitempty" json:"_property,omitempty"`
	Op                FilterOperator    `bson:"op" json:"op"`
	OpElement         *PrimitiveElement `bson:"_op,omitempty" json:"_op,omitempty"`
	Value             string            `bson:"value" json:"value"`
	ValueElement      *PrimitiveElement `bson:"_value,omitempty" json:"_value,omitempty"`
}
type ValueSetExpansion struct {
	Id                *string                      `bson:"id,omitempty" json:"id,omitempty"`
	IdElement         *PrimitiveElement            `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension         []Extension                  `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension                  `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Identifier        *string                      `bson:"identifier,omitempty" json:"identifier,omitempty"`
	IdentifierElement *PrimitiveElement            `bson:"_identifier,omitempty" json:"_identifier,omitempty"`
	Timestamp         string                       `bson:"timestamp" json:"timestamp"`
	TimestampElement  *PrimitiveElement            `bson:"_timestamp,omitempty" json:"_timestamp,omitempty"`
	Total             *int                         `bson:"total,omitempty" json:"total,omitempty"`
	TotalElement      *PrimitiveElement            `bson:"_total,omitempty" json:"_total,omitempty"`
	Offset            *int                         `bson:"offset,omitempty" json:"offset,omitempty"`
	OffsetElement     *PrimitiveElement            `bson:"_offset,omitempty" json:"_offset,omitempty"`
	Parameter         []ValueSetExpansionParameter `bson:"parameter,omitempty" json:"parameter,omitempty"`
	Contains          []ValueSetExpansionContains  `bson:"contains,omitempty" json:"contains,omitempty"`
}
type ValueSetExpansionParameter struct {
	Id                   *string           `bson:"id,omitempty" json:"id,omitempty"`
	IdElement            *PrimitiveElement `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension            []Extension       `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension    []Extension       `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Name                 string            `bson:"name" json:"name"`
	NameElement          *PrimitiveElement `bson:"_name,omitempty" json:"_name,omitempty"`
	ValueString          *string           `bson:"valueString,omitempty" json:"valueString,omitempty"`
	ValueStringElement   *PrimitiveElement `bson:"_valueString,omitempty" json:"_valueString,omitempty"`
	ValueBoolean         *bool             `bson:"valueBoolean,omitempty" json:"valueBoolean,omitempty"`
	ValueBooleanElement  *PrimitiveElement `bson:"_valueBoolean,omitempty" json:"_valueBoolean,omitempty"`
	ValueInteger         *int              `bson:"valueInteger,omitempty" json:"valueInteger,omitempty"`
	ValueIntegerElement  *PrimitiveElement `bson:"_valueInteger,omitempty" json:"_valueInteger,omitempty"`
	ValueDecimal         *json.Number      `bson:"valueDecimal,omitempty" json:"valueDecimal,omitempty"`
	ValueDecimalElement  *PrimitiveElement `bson:"_valueDecimal,omitempty" json:"_valueDecimal,omitempty"`
	ValueUri             *string           `bson:"valueUri,omitempty" json:"valueUri,omitempty"`
	ValueUriElement      *PrimitiveElement `bson:"_valueUri,omitempty" json:"_valueUri,omitempty"`
	ValueCode            *string           `bson:"valueCode,omitempty" json:"valueCode,omitempty"`
	ValueCodeElement     *PrimitiveElement `bson:"_valueCode,omitempty" json:"_valueCode,omitempty"`
	ValueDateTime        *string           `bson:"valueDateTime,omitempty" json:"valueDateTime,omitempty"`
	ValueDateTimeElement *PrimitiveElement `bson:"_valueDateTime,omitempty" json:"_valueDateTime,omitempty"`
}
type ValueSetExpansionContains struct {
	Id                *string                                    `bson:"id,omitempty" json:"id,omitempty"`
	IdElement         *PrimitiveElement                          `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension         []Extension                                `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension                                `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	System            *string                                    `bson:"system,omitempty" json:"system,omitempty"`
	SystemElement     *PrimitiveElement                          `bson:"_system,omitempty" json:"_system,omitempty"`
	Abstract          *bool                                      `bson:"abstract,omitempty" json:"abstract,omitempty"`
	AbstractElement   *PrimitiveElement                          `bson:"_abstract,omitempty" json:"_abstract,omitempty"`
	Inactive          *bool                                      `bson:"inactive,omitempty" json:"inactive,omitempty"`
	InactiveElement   *PrimitiveElement                          `bson:"_inactive,omitempty" json:"_inactive,omitempty"`
	Version           *string                                    `bson:"version,omitempty" json:"version,omitempty"`
	VersionElement    *PrimitiveElement                          `bson:"_version,omitempty" json:"_version,omitempty"`
	Code              *string                                    `bson:"code,omitempty" json:"code,omitempty"`
	CodeElement       *PrimitiveElement                          `bson:"_code,omitempty" json:"_code,omitempty"`
	Display           *string                                    `bson:"display,omitempty" json:"display,omitempty"`
	DisplayElement    *PrimitiveElement                          `bson:"_display,omitempty" json:"_display,omitempty"`
	Designation       []ValueSetComposeIncludeConceptDesignation `bson:"designation,omitempty" json:"designation,omitempty"`
	Contains          []ValueSetExpansionContains                `bson:"contains,omitempty" json:"contains,omitempty"`
}
type OtherValueSet ValueSet

// MarshalJSON marshals the given ValueSet as JSON into a byte slice
func (r ValueSet) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		OtherValueSet
		ResourceType string `json:"resourceType"`
	}{
		OtherValueSet: OtherValueSet(r),
		ResourceType:  "ValueSet",
	})
}

// UnmarshalValueSet unmarshals a ValueSet.
func UnmarshalValueSet(b []byte) (ValueSet, error) {
	var valueSet ValueSet
	if err := json.Unmarshal(b, &valueSet); err != nil {
		return valueSet, err
	}
	return valueSet, nil
}
