// Copyright 2019 - 2022 The Samply Community
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir

import "encoding/json"

// THIS FILE IS GENERATED BY https://github.com/samply/golang-fhir-models
// PLEASE DO NOT EDIT BY HAND

// VisionPrescription is documented here http://hl7.org/fhir/StructureDefinition/VisionPrescription
type VisionPrescription struct {
	Id                   *string                               `bson:"id,omitempty" json:"id,omitempty"`
	IdElement            *PrimitiveElement                     `bson:"_id,omitempty" json:"_id,omitempty"`
	Meta                 *Meta                                 `bson:"meta,omitempty" json:"meta,omitempty"`
	ImplicitRules        *string                               `bson:"implicitRules,omitempty" json:"implicitRules,omitempty"`
	ImplicitRulesElement *PrimitiveElement                     `bson:"_implicitRules,omitempty" json:"_implicitRules,omitempty"`
	Language             *string                               `bson:"language,omitempty" json:"language,omitempty"`
	LanguageElement      *PrimitiveElement                     `bson:"_language,omitempty" json:"_language,omitempty"`
	Text                 *Narrative                            `bson:"text,omitempty" json:"text,omitempty"`
	Extension            []Extension                           `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension    []Extension                           `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Identifier           []Identifier                          `bson:"identifier,omitempty" json:"identifier,omitempty"`
	Status               FinancialResourceStatusCodes          `bson:"status" json:"status"`
	StatusElement        *PrimitiveElement                     `bson:"_status,omitempty" json:"_status,omitempty"`
	Created              string                                `bson:"created" json:"created"`
	CreatedElement       *PrimitiveElement                     `bson:"_created,omitempty" json:"_created,omitempty"`
	Patient              Reference                             `bson:"patient" json:"patient"`
	Encounter            *Reference                            `bson:"encounter,omitempty" json:"encounter,omitempty"`
	DateWritten          string                                `bson:"dateWritten" json:"dateWritten"`
	DateWrittenElement   *PrimitiveElement                     `bson:"_dateWritten,omitempty" json:"_dateWritten,omitempty"`
	Prescriber           Reference                             `bson:"prescriber" json:"prescriber"`
	LensSpecification    []VisionPrescriptionLensSpecification `bson:"lensSpecification" json:"lensSpecification"`
}
type VisionPrescriptionLensSpecification struct {
	Id                *string                                    `bson:"id,omitempty" json:"id,omitempty"`
	IdElement         *PrimitiveElement                          `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension         []Extension                                `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension                                `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Product           CodeableConcept                            `bson:"product" json:"product"`
	Eye               VisionEyes                                 `bson:"eye" json:"eye"`
	EyeElement        *PrimitiveElement                          `bson:"_eye,omitempty" json:"_eye,omitempty"`
	Sphere            *json.Number                               `bson:"sphere,omitempty" json:"sphere,omitempty"`
	SphereElement     *PrimitiveElement                          `bson:"_sphere,omitempty" json:"_sphere,omitempty"`
	Cylinder          *json.Number                               `bson:"cylinder,omitempty" json:"cylinder,omitempty"`
	CylinderElement   *PrimitiveElement                          `bson:"_cylinder,omitempty" json:"_cylinder,omitempty"`
	Axis              *int                                       `bson:"axis,omitempty" json:"axis,omitempty"`
	AxisElement       *PrimitiveElement                          `bson:"_axis,omitempty" json:"_axis,omitempty"`
	Prism             []VisionPrescriptionLensSpecificationPrism `bson:"prism,omitempty" json:"prism,omitempty"`
	Add               *json.Number                               `bson:"add,omitempty" json:"add,omitempty"`
	AddElement        *PrimitiveElement                          `bson:"_add,omitempty" json:"_add,omitempty"`
	Power             *json.Number                               `bson:"power,omitempty" json:"power,omitempty"`
	PowerElement      *PrimitiveElement                          `bson:"_power,omitempty" json:"_power,omitempty"`
	BackCurve         *json.Number                               `bson:"backCurve,omitempty" json:"backCurve,omitempty"`
	BackCurveElement  *PrimitiveElement                          `bson:"_backCurve,omitempty" json:"_backCurve,omitempty"`
	Diameter          *json.Number                               `bson:"diameter,omitempty" json:"diameter,omitempty"`
	DiameterElement   *PrimitiveElement                          `bson:"_diameter,omitempty" json:"_diameter,omitempty"`
	Duration          *Quantity                                  `bson:"duration,omitempty" json:"duration,omitempty"`
	Color             *string                                    `bson:"color,omitempty" json:"color,omitempty"`
	ColorElement      *PrimitiveElement                          `bson:"_color,omitempty" json:"_color,omitempty"`
	Brand             *string                                    `bson:"brand,omitempty" json:"brand,omitempty"`
	BrandElement      *PrimitiveElement                          `bson:"_brand,omitempty" json:"_brand,omitempty"`
	Note              []Annotation                               `bson:"note,omitempty" json:"note,omitempty"`
}
type VisionPrescriptionLensSpecificationPrism struct {
	Id                *string           `bson:"id,omitempty" json:"id,omitempty"`
	IdElement         *PrimitiveElement `bson:"_id,omitempty" json:"_id,omitempty"`
	Extension         []Extension       `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension       `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Amount            json.Number       `bson:"amount" json:"amount"`
	AmountElement     *PrimitiveElement `bson:"_amount,omitempty" json:"_amount,omitempty"`
	Base              VisionBase        `bson:"base" json:"base"`
	BaseElement       *PrimitiveElement `bson:"_base,omitempty" json:"_base,omitempty"`
}
type OtherVisionPrescription VisionPrescription

// MarshalJSON marshals the given VisionPrescription as JSON into a byte slice
func (r VisionPrescription) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		OtherVisionPrescription
		ResourceType string `json:"resourceType"`
	}{
		OtherVisionPrescription: OtherVisionPrescription(r),
		ResourceType:            "VisionPrescription",
	})
}

// UnmarshalVisionPrescription unmarshals a VisionPrescription.
func UnmarshalVisionPrescription(b []byte) (VisionPrescription, error) {
	var visionPrescription VisionPrescription
	if err := json.Unmarshal(b, &visionPrescription); err != nil {
		return visionPrescription, err
	}
	return visionPrescription, nil
}
